import fs from 'node:fs/promises';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {rolldown}=await import(pathToFileURL(require.resolve('rolldown',{paths:[require.resolve('vite')]})).href);
const b=await rolldown({input:'work/portable-api.ts',platform:'node'});
const output=await b.generate({format:'esm'});await fs.mkdir('work/test-build',{recursive:true});await fs.writeFile('work/test-build/portable.mjs',output.output[0].code);
const {createNotebookRequest,freshNotebook}=await import('./test-build/portable.mjs');globalThis.location={search:''};
let saved=null,fail=false;const req=createNotebookRequest({read:async()=>saved?structuredClone(saved):null,write:async s=>{if(fail)throw Error('not saved');saved=structuredClone(s)},member:()=>({id:'alice',email:'alice@example.test',status:'account'})});
assert.equal((await req('bootstrap')).member.id,'alice');
await req('records',{kind:'bottle',id:'wine',data:{name:'Test wine',vintage:'2020',style:'Red',qty:2,currency:'USD'}});
assert.equal(saved.records.length,1);fail=true;await assert.rejects(req('profile',{name:'lost'}));assert.notEqual(saved.name,'lost');fail=false;
await req('import',{bottles:[{id:'wine',name:'duplicate',qty:99},{id:'new',name:'New wine',vintage:'NV',style:'White',qty:1}],notes:[],gatherings:[]});assert.equal(saved.records.length,2);assert.equal(saved.records.find(r=>r.id==='wine').data.qty,2);
await req('profile',{name:'Alice',currency:'EUR'});assert.equal((await req('bootstrap')).member.name,'Alice');
const bob=createNotebookRequest({read:async()=>null,write:async()=>{},member:()=>({id:'bob',status:'account'})});assert.equal((await bob('bootstrap')).records.length,0);
assert.equal((await req('bootstrap')).plans.length,0);
console.log('PASS: account identity, remote save acknowledgement, failure preservation, duplicate-safe import, separate notebooks, pricing disabled.');
const cloudBundle=await rolldown({input:'lib/account-store.ts',platform:'node',plugins:[{name:'mock-sdk',transform(code,id){if(id.replaceAll('\\','/').endsWith('/account-store.ts'))return code.replace("import {createClient} from '@supabase/supabase-js';","const createClient=()=>globalThis.__testClient;");}}]});
const cloudOutput=await cloudBundle.generate({format:'esm'});await fs.writeFile('work/test-build/cloud.mjs',cloudOutput.output[0].code);
globalThis.window={DECANT_SUPABASE:{url:'https://example.test',publishableKey:'public'}};
let response={data:{revision:2},error:null},filters=[],during=null;
const query={select(){return this},eq(k,v){filters.push([k,v]);return this},insert(){return this},update(){return this},async maybeSingle(){if(during)during();return response}};
globalThis.__testClient={from:()=>query};const cloud=await import('./test-build/cloud.mjs');cloud.setAccount({id:'alice'});
await cloud.writeCloud('alice',{},1);assert.deepEqual(filters,[['user_id','alice'],['revision',1]]);
response={data:null,error:null};await assert.rejects(cloud.writeCloud('alice',{},1),/another device/);
response={data:null,error:{code:'23505'}};await assert.rejects(cloud.writeCloud('alice',{},null),/another device/);
response={data:null,error:{code:'network'}};await assert.rejects(cloud.writeCloud('alice',{},1),/not saved/);
response={data:{notebook:{name:'Alice'},revision:2},error:null};during=()=>cloud.setAccount({id:'bob'});await assert.rejects(cloud.readCloud('alice'),/sign-in changed/);
await assert.rejects(cloud.writeCloud('alice',{},2),/sign-in changed/);
console.log('PASS: owner filtering, revision checks, concurrent-create conflicts, write failure, session-change race guards.');
