import React,{useEffect,useRef,useState} from 'react';
let loading:Promise<any>|null=null;
function loadReader(){if((window as any).Tesseract)return Promise.resolve((window as any).Tesseract);if(!loading)loading=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/tesseract.js@6.0.1/dist/tesseract.min.js';script.onload=()=>resolve((window as any).Tesseract);script.onerror=()=>{loading=null;script.remove();reject(new Error('The label reader could not load. Check your connection or search by name.'))};document.head.appendChild(script)});return loading}
export function LabelScan({onRead}:{onRead:(query:string,vintage:string)=>void}){
 const [busy,setBusy]=useState(false),[status,setStatus]=useState(''),[text,setText]=useState(''),[query,setQuery]=useState(''),[vintage,setVintage]=useState(''),[preview,setPreview]=useState('');const worker=useRef<any>(null),alive=useRef(true),generation=useRef(0);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;generation.current++;worker.current?.terminate()}},[]);
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
 async function scan(file?:File){if(!file)return;if(file.size>20000000){setStatus('Choose a photo smaller than 20 MB.');return}const id=++generation.current;setBusy(true);setText('');setQuery('');setStatus('Loading label reader…');setPreview(URL.createObjectURL(file));let reader:any;try{const api=await loadReader();if(!alive.current||id!==generation.current)return;reader=await api.createWorker('eng',1,{logger:(m:any)=>{if(alive.current&&id===generation.current&&m.status==='recognizing text')setStatus('Reading label… '+Math.round(m.progress*100)+'%')}});worker.current=reader;if(!alive.current||id!==generation.current)return;const result=await reader.recognize(file);if(!alive.current||id!==generation.current)return;const raw=result.data.text.trim();setText(raw);const year=raw.match(/\b(?:19|20)\d{2}\b/g)?.find((y:string)=>Number(y)<=new Date().getFullYear())||(/\bN\.?V\.?\b/i.test(raw)?'NV':'');setVintage(year);const lines=raw.split('\n').map((l:string)=>l.replace(/\b(?:19|20)\d{2}\b/g,'').replace(/[^\p{L}\s'-]/gu,' ').replace(/\s+/g,' ').trim()).filter((l:string)=>l.length>3&&!/bottled|contains|sulfite|sulphite|alcohol|imported|warning|product of|mis en bouteille/i.test(l));const suggestion=lines.slice(0,2).join(' ').slice(0,100);setQuery(suggestion);setStatus(raw?'Review the search words, then find the matching LWIN wine. Confirm the year against your label.':'No readable text found. Try a straight-on photo in good light.');}catch{if(alive.current&&id===generation.current)setStatus('We could not read this photo. Try a clear JPG or PNG, or search by name.')}finally{await reader?.terminate().catch(()=>{});if(worker.current===reader)worker.current=null;if(alive.current&&id===generation.current)setBusy(false)}}
 return <section className="label-scan wide"><h3>Start with the label</h3><p className="small">Your photo stays on your device. Review the search words, then confirm a matching wine from the catalog.</p><div className="scan-actions"><label className="outline-button file-label" role="button" tabIndex={0} aria-disabled={busy} onKeyDown={e=>{if(!busy&&(e.key==='Enter'||e.key===' ')){e.preventDefault();e.currentTarget.querySelector('input')?.click()}}}>Take a photo<input type="file" accept="image/*" capture="environment" disabled={busy} onChange={e=>{scan(e.target.files?.[0]);e.target.value=''}}/></label><label className="outline-button file-label" role="button" tabIndex={0} aria-disabled={busy} onKeyDown={e=>{if(!busy&&(e.key==='Enter'||e.key===' ')){e.preventDefault();e.currentTarget.querySelector('input')?.click()}}}>Choose a photo<input type="file" accept="image/*" disabled={busy} onChange={e=>{scan(e.target.files?.[0]);e.target.value=''}}/></label></div>{preview&&<img src={preview} alt="Label selected for reading"/>}<p role="status">{status}</p>{text&&<><details><summary>Text read from the label</summary><p className="scan-text">{text}</p></details><label className="field">Producer or wine to search<input value={query} maxLength={100} onChange={e=>setQuery(e.target.value)}/></label><label className="field">Year read from label<input value={vintage} onChange={e=>setVintage(e.target.value)}/></label><button type="button" className="outline-button" disabled={query.trim().length<2} onClick={()=>onRead(query.trim(),vintage)}>Find matching wines</button><p className="small">Choose a catalog result to fill producer, name and region. Check all details before saving.</p></>}</section>
}
