import React,{useEffect,useState} from 'react';
import {supabase} from '../lib/account-store';
export async function social(action:string,target='',payload:any={}){
 if(!supabase)throw new Error('Sign-in setup is unavailable.');
 const {data,error}=await supabase.rpc('decant_social',{action,target,payload});
 if(error){if(error.code==='PGRST202')throw new Error('Friends are being set up. Please try again shortly.');if(error.code==='23505')throw new Error('That username is already taken.');throw new Error(error.message||'Please try again.');}return data;
}
const profileUrl=(username:string)=>location.origin+location.pathname+'?profile='+encodeURIComponent(username);
export function SocialPanel({records}:{records:any[]}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[username,setUsername]=useState(''),[name,setName]=useState(''),[visibility,setVisibility]=useState('private'),[search,setSearch]=useState(''),[found,setFound]=useState<any>(null);
 async function load(){const d=await social('home');setData(d);return d;}
 useEffect(()=>{let alive=true;social('home').then(d=>{if(!alive)return;setData(d);setUsername(d.profile?.username||'');setName(d.profile?.display_name||'');setVisibility(d.profile?.visibility||'private')}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false}},[]);
 async function act(fn:()=>Promise<any>,message=''){setBusy(true);setError('');setNotice('');try{await fn();await load();setNotice(message)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const action=(a:string,u:string)=>act(()=>social(a,u));
 return <section className="social-panel panel"><h2>Friends & sharing</h2>{error&&<p role="alert">{error}<button className="text-button" disabled={busy} onClick={()=>act(load)}>Try again</button></p>}{notice&&<p role="status">{notice}</p>}
 {data&&<><form className="form-grid" onSubmit={e=>{e.preventDefault();act(()=>social('profile','',{username,display_name:name,visibility}),'Profile and privacy saved.')}}>
 <label className="field">Username<input required minLength={3} maxLength={24} pattern="[a-z0-9_]{3,24}" value={username} onChange={e=>setUsername(e.target.value.toLowerCase())} autoCapitalize="none" spellCheck={false}/><span className="small">3–24 lowercase letters, numbers, or underscores. People can find your profile by this name.</span></label>
 <label className="field">Display name<input maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label>
 <label className="field wide">Who can see your collection?<select value={visibility} onChange={e=>setVisibility(e.target.value)}><option value="private">Private — only me</option><option value="friends">Share all with friends — accepted friends only</option><option value="public">Public — anyone with my profile link</option></select></label>
 <p className="small wide">{visibility==='private'?'Your collection is hidden from other people.':visibility==='friends'?'Saving shares existing and future bottles, tasting notes, and ratings with accepted friends.':'Saving makes existing and future bottles, tasting notes, and ratings publicly visible without sign-in.'} Entries marked private below are excluded. Email, prices, storage locations, hosting details, and lesson notes are never shared. Tasting-note text is included, so remove personal details before sharing.</p>
 <button className="primary" disabled={busy}>Save profile & privacy</button></form>
 {data.profile&&<><p><a href={profileUrl(data.profile.username)}>View my shared profile ↗</a></p><button className="text-button" disabled={busy} onClick={()=>act(async()=>{await navigator.clipboard.writeText(profileUrl(data.profile.username))},'Profile link copied.')}>Copy profile link</button>
 <hr/><h3>Find a friend</h3><form className="account-actions" onSubmit={e=>{e.preventDefault();setFound(null);act(async()=>setFound(await social('lookup',search.replace(/^@/,''))))}}><label className="field">Exact username<input required value={search} onChange={e=>{setSearch(e.target.value);setFound(null)}} placeholder="username" autoCapitalize="none"/></label><button className="outline-button" disabled={busy}>Find person</button></form>
 {found&&(found.unavailable?<p>No profile found.</p>:<div className="social-person"><a href={profileUrl(found.username)}>{found.display_name||found.username} · @{found.username}</a>{!found.self&&<><button className="text-button" disabled={busy||found.friend} onClick={()=>act(()=>social('request',found.username),'Request sent, or already pending. Check your list below.')}>{found.friend?'Friends':'Add friend'}</button><button className="text-button" disabled={busy} onClick={()=>act(async()=>{await social('block',found.username);setFound(null)},'Person blocked.')}>Block</button></>}</div>)}
 <h3>Your friends & requests</h3>{!data.friends.length&&<p>No friends or requests yet.</p>}{data.friends.map((p:any)=><div className="social-person" key={p.username}><a href={profileUrl(p.username)}>{p.display_name||p.username} · @{p.username}</a><span>{p.status==='accepted'?'Friends':p.incoming?'Wants to add you':'Request sent'}</span><div className="account-actions">{p.status==='pending'&&p.incoming?<><button className="outline-button" disabled={busy} onClick={()=>action('accept',p.username)}>Accept</button><button className="text-button" disabled={busy} onClick={()=>action('decline',p.username)}>Decline</button></>:<button className="text-button" disabled={busy} onClick={()=>action(p.status==='accepted'?'remove':'cancel',p.username)}>{p.status==='accepted'?'Remove friend':'Cancel request'}</button>}<button className="text-button" disabled={busy} onClick={()=>action('block',p.username)}>Block</button></div></div>)}
 {!!data.blocked.length&&<details><summary>Blocked people</summary>{data.blocked.map((p:any)=><div className="social-person" key={p.username}>@{p.username}<button disabled={busy} className="text-button" onClick={()=>action('unblock',p.username)}>Unblock</button></div>)}</details>}
 <hr/><h3>Keep individual entries private</h3><p className="small">These overrides apply in both Friends only and Public mode. Bottle notes and learning reflections are excluded automatically.</p><div className="social-entries">{records.filter(r=>(r.kind==='bottle'||r.kind==='note')&&r.data.noteType!=='lesson'&&!r.data.lessonId&&!String(r.data.name).startsWith('Reflection:')).map(r=><label className="social-person" key={r.id}><span>{r.data.name||'Untitled'} · {r.kind==='bottle'?'Bottle':'Tasting note'}</span><span><input type="checkbox" checked={data.private_entries.includes(r.id)} disabled={busy} onChange={e=>act(()=>social('entry','',{entry_id:r.id,private:e.target.checked}))}/> Keep private</span></label>)}</div>
 </>}
 </>}
 </section>;
}
export function SharedProfile({username}:{username:string}){
 const [data,setData]=useState<any>(null),[error,setError]=useState('');
 useEffect(()=>{let alive=true;social('view',username).then(d=>{if(alive)setData(d)}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false}},[username]);
 return <main className="shared-profile"><a className="brand" href={location.pathname}>decant</a><p><a href={location.pathname+'?view=account'}>My notebook & sign-in</a></p>{error?<p role="alert">{error}</p>:!data?<p>Opening profile…</p>:data.unavailable?<h1>Profile unavailable</h1>:<><h1>{data.display_name||data.username}</h1><p>@{data.username}</p>{!data.can_view?<p>This collection is private or available to accepted friends. If you are a friend, sign in to view it.</p>:<>{!data.entries.length&&<p>No shared entries yet.</p>}<div className="bottle-grid">{data.entries.map((e:any,i:number)=><article className="bottle-card" key={i}><span className="eyebrow">{e.kind==='bottle'?'Cellar':'Tasting note'}</span><h2>{e.name||'Untitled wine'}</h2><p>{[e.producer,e.vintage,e.region,e.grape].filter(Boolean).join(' · ')}</p>{e.kind==='note'&&<><p>{e.rating?e.rating+' / 5':''} {e.date}</p><p className="shared-note">{e.note}</p></>}</article>)}</div></>}</>}</main>;
}
