import React,{useId,useState} from 'react';
export function YearPicker({label,value,onChange,vintage=false,placeholder,readOnly=false}:{label:string;value:string;onChange:(v:string)=>void;vintage?:boolean;placeholder?:string;readOnly?:boolean}){
 const id=useId(),[open,setOpen]=useState(false),[typing,setTyping]=useState(false),[active,setActive]=useState(-1);
 const current=new Date().getFullYear(),years=vintage?['NV',...Array.from({length:current-1979},(_,i)=>String(current-i))]:[...Array.from({length:Math.max(0,2060-current+1)},(_,i)=>String(current+i)),...Array.from({length:current-1980},(_,i)=>String(current-i-1))];
 const options=years.filter(y=>!typing||y.toLowerCase().includes(String(value||'').toLowerCase()));
 const custom=/^\d{4}$/.test(value||'')&&!years.includes(value)&&(!vintage||Number(value)<1980);
 const shown=custom?[...options,value]:options;
 const choose=(v:string)=>{onChange(v);setOpen(false);setTyping(false);setActive(-1)};
 return <div className="field year-picker"><label htmlFor={id}>{label}</label><input id={id} role="combobox" aria-autocomplete="list" aria-controls={id+'-options'} aria-expanded={open&&!readOnly} aria-activedescendant={open&&active>=0?id+'-'+active:undefined} autoComplete="off" readOnly={readOnly} value={value||''} placeholder={placeholder||'Select or type a year'} onFocus={()=>{if(!readOnly){setOpen(true);setTyping(false);setActive(-1)}}} onClick={()=>!readOnly&&setOpen(true)} onBlur={()=>setOpen(false)} onChange={e=>{onChange(e.target.value);setTyping(true);setActive(-1);setOpen(true)}} onKeyDown={e=>{if(e.key==='Escape'&&open){e.preventDefault();e.stopPropagation();setOpen(false)}if(['ArrowDown','ArrowUp'].includes(e.key)&&!readOnly){e.preventDefault();setOpen(true);const next=e.key==='ArrowDown'?Math.min(active+1,shown.length-1):Math.max(active-1,0);setActive(next);document.getElementById(id+'-'+next)?.scrollIntoView({block:'nearest'})}if(e.key==='Enter'&&open){e.preventDefault();if(active>=0&&shown[active])choose(shown[active]);else if(shown.length===1)choose(shown[0]);else setOpen(false)}}}/>{open&&!readOnly&&<ul id={id+'-options'} role="listbox" aria-label={label+' options'}>{shown.map((year,i)=><li id={id+'-'+i} key={year} role="option" aria-selected={active===i} onMouseDown={e=>e.preventDefault()} onClick={()=>choose(year)}>{year}{custom&&year===value?' · custom':''}</li>)}{!shown.length&&<li role="presentation">{vintage?'Enter a full year before 1980 for a custom vintage.':'Type a four-digit year.'}</li>}</ul>}</div>
}
