import {type WineReference,type WineStyle,pretty,FIELDS} from './academy-engine.ts';
export type Block={block:'prose'|'callout'|'prompt'|'term';text?:string;term?:string;gloss?:string};
export type AcademyLesson={id:string;type:'lesson'|'article';track:'structured'|'deductive'|'both';tier:1|2|3;title:string;summary:string;topics:string[];regions:string[];grapes:string[];access:'open';estMinutes:number;requires:string[];body:Block[];checks:{type:'mcq';stem:string;options:string[];answer:number;why:string}[];recall:{front:string;back:string}[];};
export const TRACK_LEVELS={structured:['Foundation','Working','Precision'],deductive:['Intro','Floor','Advanced']};
export const academyLessons:AcademyLesson[]=[
 {id:'systematic-method',type:'lesson',track:'both',tier:1,title:'A systematic way to taste',summary:'Four passes, same order every time. The habit behind everything else in the Academy.',topics:['method','appearance','nose','palate','conclusions'],regions:[],grapes:[],access:'open',estMinutes:8,requires:[],body:[
 {block:'prose',text:'Left to itself, a glass of wine gives you whatever shouts loudest. Working through it in a set order means you notice the same things every time, which is what makes two tastings worth comparing. Four passes: look, smell, taste, then put it together. Same order for a Tuesday bottle as for a blind sample.'},
 {block:'prose',text:'The order is not arbitrary. Color hints at weight and age. Aroma gives you words while your palate is still fresh. The physical stuff, acidity and tannin and body, is easiest to judge early, before you go hunting for flavor detail. Conclusions come last because they are the only step that gets to use everything.'},
 {block:'term',term:'Pass',gloss:'One trip through a single sense, finished before the next begins. Four passes make one complete note.'},
 {block:'prose',text:'Look. Hold the glass over something plain, tilt it, and read the rim. Clarity, how deep the color is, which color it is. That is the whole pass. Color tells you less about quality than it seems to, so save your conclusions for later.'},
 {block:'prose',text:'Smell. Swirl, then take short sniffs; your nose tires within seconds and one long inhale gives you less. Check it smells sound, then how strong it is, then whether it smells young or older, then what is actually in there. Five words is a good target, and specific beats fancy. Raspberry, not red fruit.'},
 {block:'prose',text:'Taste. Enough to coat your whole mouth. One call at a time, with a pause between: sweetness, acidity, tannin on reds, alcohol, body, flavor intensity, finish. Count the finish after you swallow or spit. Flavors come last, and plenty of overlap with the nose is normal.'},
 {block:'prose',text:'Conclude. How good is it, and when should it be opened. Both of these work best when you can point back at something from the first three passes. If you cannot, that is usually a sign to go back and look again rather than to write something down anyway.'},
 {block:'callout',text:'Two habits worth picking up. Write a call down before you say it out loud, because we all defend an opinion once we have heard ourselves make it. And when you are torn, pick the closer answer rather than nothing; you can learn from a call you got wrong.'},
 {block:'prose',text:'The same words every time is what makes your notes comparable. Decant sets the scales: three steps for color intensity and alcohol, five for acidity, tannin, body, aroma intensity, flavor intensity and finish. Pick one step rather than a range, and say the rest in your own words underneath.'},
 {block:'prose',text:'This is Decant’s own scheme rather than any exam board’s, and the practice cases are one person’s answer rather than the truth about a wine. Disagreeing with one is allowed.'},
 {block:'prompt',text:'Tonight I am tasting ___. The pass I tend to rush is ___. The call I find hardest is ___.'}],checks:[
 {type:'mcq',stem:'Why does structure come before naming flavors?',options:['Flavors are less important than structure','Your palate is freshest early, and structure is a physical sensation that fades with fatigue','Because flavors cannot be judged until you know the grape'],answer:1,why:'Those calls are easiest on a fresh mouth. Going hunting for flavor detail first tires your palate out.'},
 {type:'mcq',stem:'You are unsure whether acidity is medium or medium (+). What does the method ask for?',options:['Leave it blank until you are certain','Record “medium to medium (+)”','Choose the closer single position and note the hesitation in your own words'],answer:2,why:'A range is hard to compare against anything later. One step, plus whatever you want to say about it in your own words.'},
 {type:'mcq',stem:'Which conclusion is built correctly?',options:['Very good, because the label is well regarded','Very good, because the finish was long and the fruit stayed clear through it','Very good, because it tastes expensive'],answer:1,why:'It points back at something in the glass. The other two come from the label and the price tag.'}],recall:[
 {front:'What are the four passes, in order?',back:'Look, smell, taste, conclude.'},
 {front:'Why a short sniff rather than a long inhale?',back:'The nose adapts within seconds, so a long inhale returns less information, not more.'},
 {front:'What must every quality or readiness conclusion rest on?',back:'Something you noticed in one of the first three passes.'},
 {front:'What does Decant ask you to do when a call is uncertain?',back:'Pick the closer of the two and say why you hesitated in your own words.'}]},
 {id:'structure-sensations',type:'lesson',track:'structured',tier:1,title:'Four things you can feel',summary:'Freshness, grip, weight and how long it lasts. Learn these four and the rest gets easier.',topics:['acidity','tannin','body','finish'],regions:[],grapes:[],access:'open',estMinutes:5,requires:[],body:[
 {block:'prose',text:'Take these one at a time. Acidity is the freshness that makes your mouth water. Tannin is the drying grip on your gums. Body is how heavy the wine feels. Finish is how long the flavor sticks around after you swallow. Worth knowing: a big smell does not mean a big body. Plenty of light wines smell enormous.'},
 {block:'callout',text:'You do not need to open anything special for this. Next glass you have, take a sip and make the four calls. A sip of water and a moment in between helps. Leave any of them blank if nothing comes.'},
 {block:'term',term:'Structure',gloss:'The way a wine feels in your mouth, as opposed to what it tastes of.'},
 {block:'prompt',text:'Freshness: ___. Drying grip: ___. Weight: ___. Flavor after the sip: ___.'}],checks:[{type:'mcq',stem:'A wine smells huge but feels light in your mouth. What is its body?',options:['Full, because its aroma is strong','Light, because body describes weight','High tannin, because it is intense'],answer:1,why:'Body is about weight in the mouth. How loud it smells is a separate question.'}],recall:[{front:'Which sensation helps you recognize acidity?',back:'Mouth-watering freshness.'},{front:'How is tannin different from acidity?',back:'Tannin dries or grips; acidity makes the mouth water.'},{front:'What does finish describe?',back:'The persistence of flavor after the wine leaves your mouth.'}]},
 {id:'structure-scales',type:'lesson',track:'structured',tier:2,title:'Choose one place on the scale',summary:'Make a clear call and give each field the scale it actually uses.',topics:['scales','alcohol','appearance'],regions:[],grapes:[],access:'open',estMinutes:6,requires:['structure-sensations'],body:[
 {block:'prose',text:'Color intensity has three steps: pale, medium, deep. Alcohol has three too: low, medium, high. Acidity, tannin, body, aroma intensity, flavor intensity and finish each have five. Pick the closest single step rather than a range, then say whatever you like about it in your own words underneath.'},
 {block:'callout',text:'Try a practice case: read the description, fill in the grid, see how it lines up. On the five-step fields, landing next door still earns half credit.'},
 {block:'prose',text:'This is Decant’s scoring, not an exam board’s. And a real bottle shifts with temperature, age and the day you open it, so treat a practice answer as one reasonable view rather than the final word.'},
 {block:'prompt',text:'The one I hesitated on is ___. I went with ___ because ___.'}],checks:[{type:'mcq',stem:'Which is a valid alcohol answer in this practice grid?',options:['Medium (+)','Medium to high','Medium'],answer:2,why:'Alcohol only has low, medium and high here. No half steps.'}],recall:[{front:'How many positions does Decant use for alcohol?',back:'Three: low, medium, high.'},{front:'What earns half credit on a five-position field?',back:'One position away from the authored reference.'}]},
 {id:'structure-descriptors',type:'lesson',track:'structured',tier:3,title:'Name the fruit, not the basket',summary:'Turn category words into specific observations and complete the conclusion.',topics:['descriptors','readiness','quality'],regions:[],grapes:[],access:'open',estMinutes:7,requires:['structure-scales'],body:[
 {block:'prose',text:'“Fruit” tells a reader almost nothing. “Raspberry” tells them a lot. Reach for whatever is familiar to you, even if it is not a classic wine word. Five aromas and three flavors is a good target here. If your word is not in the practice answer, that does not make it wrong, it just means this exercise cannot check it.'},
 {block:'term',term:'Primary / secondary / tertiary',gloss:'A way of sorting what you smell by where it came from: the grape, the winemaking, or age.'},
 {block:'callout',text:'Try it with raspberry, vanilla and leather. Three rows, one tag each. Worth remembering that a familiar smell is a clue rather than proof, since more than one thing can produce it.'},
 {block:'prose',text:'Then finish with quality and readiness. It is worth separating “drink now, this is as good as it gets” from “drinking well, and it has room to grow.”'},
 {block:'prompt',text:'Specific aromas: ___. Flavors: ___. Ready now because ___. Further development seems ___.'}],checks:[{type:'mcq',stem:'Which entry is a specific descriptor rather than a category?',options:['Red fruit','Raspberry','Spice'],answer:1,why:'Raspberry names an individual aroma. Red fruit and spice group many possibilities together.'}],recall:[{front:'Why does “red fruit” not earn a descriptor mark here?',back:'It is a category. Name a specific fruit such as raspberry.'},{front:'Does an unmatched descriptor prove your own tasting is wrong?',back:'No. This exercise scores agreement with an authored case, not a universal sensory truth.'}]},
 {id:'deduction-observe',type:'lesson',track:'deductive',tier:1,title:'Observe before naming',summary:'Build a small set of possibilities from the evidence in front of you.',topics:['deduction','structure','evidence'],regions:[],grapes:[],access:'open',estMinutes:5,requires:[],body:[
 {block:'prose',text:'Hold off on naming it. Get color, freshness, grip, weight and a few aromas down first, then put up two candidates rather than one. Ask what fits each and what does not. The trouble with a confident first guess is how quickly you start defending it.'},
 {block:'callout',text:'Use one of the written mystery cases, or have someone cover the label on a bottle you were opening anyway. Three minutes is plenty. Saying your observations out loud helps more than you would think.'},
 {block:'prompt',text:'I observed ___. Possibility A: ___. Possibility B: ___. The evidence that separates them is ___.'}],checks:[{type:'mcq',stem:'What should come before a grape guess?',options:['A familiar producer name','A set of independent observations','The expected price'],answer:1,why:'Observations give you something to test. A name gives you something to defend.'}],recall:[{front:'Why keep a second deduction possibility?',back:'It keeps you weighing the evidence instead of defending your first answer.'}]},
 {id:'deduction-chain',type:'lesson',track:'deductive',tier:2,title:'Make the reasoning audible',summary:'Connect observations to a grape and place, while keeping uncertainty visible.',topics:['deduction','region','country'],regions:['Bordeaux','Burgundy','Piedmont','Marlborough'],grapes:['Cabernet Sauvignon','Pinot Noir','Nebbiolo','Sauvignon Blanc'],access:'open',estMinutes:7,requires:['deduction-observe'],body:[
 {block:'prose',text:'Keep the chain short: what you noticed, what might explain it, what you conclude. A drying grip is something you noticed. A grape is a guess at why. A region needs more than one clue behind it. Then say what would change your mind.'},
 {block:'callout',text:'Practice saying: “I favor ___ because ___ and ___. I considered ___, but ___ makes it less likely.” A concise chain is more useful than a long list of disconnected tasting words.'},
 {block:'prose',text:'Decant scores the five final calls: grape, region, country, vintage, quality. Your reasoning is saved for you to read back, not marked, because no lookup table can fairly judge an argument.'},
 {block:'prompt',text:'I favor ___ because ___ and ___. I considered ___, but ___. My confidence is ___.'}],checks:[{type:'mcq',stem:'What does the deterministic deduction score assess?',options:['Spoken confidence','Service performance','The five conclusion fields'],answer:2,why:'The reasoning is saved for reflection. Conclusion matching cannot assess a live service performance or the quality of a spoken argument.'}],recall:[{front:'What are the five scored deduction calls?',back:'Grape, region, country, vintage and quality.'}]},
 {id:'deduction-calibrate',type:'lesson',track:'deductive',tier:3,title:'Review the misses',summary:'Use repeat practice to spot a habit rather than chase a perfect score.',topics:['calibration','review','uncertainty'],regions:[],grapes:[],access:'open',estMinutes:6,requires:['deduction-chain'],body:[
 {block:'prose',text:'When you review a miss, separate what you sensed from what you concluded. If your acidity was close but the region was wrong, the gap is in the reasoning, not the palate. Leave the old attempt alone so the next one has something honest to sit beside.'},
 {block:'callout',text:'After ten full bottle attempts against an exact reference, calibration has enough to say something. If your calls lean the same way every time, that is worth knowing. Repeating one case is fine for the habit, though remembering its answer is not the same as tasting better.'},
 {block:'prose',text:'A few recall cards a day is enough. “Again” when it did not come back, “Got it” when it did. Your own cellar details turn up in the deck, so the questions are about wine you actually own.'},
 {block:'prompt',text:'My recurring miss is ___. The evidence I should notice earlier is ___. Next time I will ___.'}],checks:[{type:'mcq',stem:'What is the most useful response to a repeated miss?',options:['Delete the old attempts','Identify the recurring decision and practice it','Only repeat the case until its answer is memorized'],answer:1,why:'Keeping the old attempts is how you tell real improvement from remembering an answer.'}],recall:[{front:'When does calibration begin?',back:'After ten full bottle-observation grids against exact bottle references, with ten valid calls for a field. Text exercises do not calibrate your palate.'}]}
];

// Original hypothetical cases. These are NOT measurements of named commercial wines.
const cases:[string,WineStyle,string,string,string,number,number,number,string[]][]=[
 ['Fresh red fruit','red','Burgundy','France','Pinot Noir',4,2,2,['raspberry','strawberry','cherry','violet','wet leaves']],
 ['Dark fruit and cedar','red','Bordeaux','France','Cabernet Sauvignon',4,4,4,['blackcurrant','plum','cedar','vanilla','leather']],
 ['Roses and firm grip','red','Piedmont','Italy','Nebbiolo',5,5,3,['rose','cherry','raspberry','leather','violet']],
 ['Pepper and dark berries','red','Northern Rhône','France','Syrah',4,4,4,['blackberry','blackcurrant','black pepper','violet','clove']],
 ['Ripe fruit and warmth','red','Barossa Valley','Australia','Shiraz',3,4,5,['blackberry','plum','black pepper','vanilla','chocolate']],
 ['Plush fruit and flowers','red','Mendoza','Argentina','Malbec',3,4,4,['plum','blackberry','violet','vanilla','clove']],
 ['Savoury red cherry','red','Tuscany','Italy','Sangiovese',5,4,3,['cherry','red plum','violet','leather','clove']],
 ['Developing red fruit','red','Rioja','Spain','Tempranillo',4,3,3,['strawberry','cherry','vanilla','leather','cedar']],
 ['Blackcurrant and weight','red','Napa Valley','United States','Cabernet Sauvignon',4,4,5,['blackcurrant','blackberry','vanilla','cedar','chocolate']],
 ['Delicate ripe cherry','red','Willamette Valley','United States','Pinot Noir',4,2,3,['cherry','raspberry','strawberry','violet','clove']],
 ['Citrus and a light frame','white','Chablis','France','Chardonnay',5,0,2,['lemon','green apple','pear','white peach','acacia']],
 ['Round orchard fruit','white','Burgundy','France','Chardonnay',4,0,4,['apple','white peach','lemon','vanilla','toast']],
 ['Tropical fruit and herbs','white','Marlborough','New Zealand','Sauvignon Blanc',5,0,2,['passion fruit','gooseberry','grapefruit','grass','green pepper']],
 ['Citrus and green notes','white','Loire Valley','France','Sauvignon Blanc',5,0,2,['lemon','grapefruit','gooseberry','grass','green apple']],
 ['Fragrant fruit and sweetness','white','Mosel','Germany','Riesling',5,0,2,['lime','green apple','white peach','honeysuckle','lemon']],
 ['Dry citrus and flowers','white','Clare Valley','Australia','Riesling',5,0,2,['lime','lemon','green apple','white peach','jasmine']],
 ['Orchard fruit and texture','white','Loire Valley','France','Chenin Blanc',5,0,3,['apple','pear','quince','honey','lemon']],
 ['Apricot and broad texture','white','Northern Rhône','France','Viognier',2,0,5,['apricot','peach','honeysuckle','orange blossom','pear']],
 ['Pale pink and citrus','rose','Provence','France','Grenache',4,0,2,['strawberry','raspberry','grapefruit','rose','white peach']],
 ['Pink fruit and fuller texture','rose','Rhône Valley','France','Grenache',3,0,4,['strawberry','raspberry','cherry','orange peel','rose']],
 ['Fresh berries and a light frame','red','Beaujolais','France','Gamay',4,1,2,['raspberry','cherry','strawberry','violet','peony']],
 ['Plum and a rounded frame','red','Bordeaux','France','Merlot',3,3,4,['plum','blackberry','cherry','cedar','leather']],
 ['Red fruit and a leafy edge','red','Loire Valley','France','Cabernet Franc',4,3,3,['raspberry','red plum','cherry','green pepper','graphite']],
 ['Fresh orchard fruit and spice','white','Niederösterreich','Austria','Grüner Veltliner',4,0,3,['green apple','pear','lemon','white pepper','acacia']],
 ['Citrus and stone fruit','white','Rías Baixas','Spain','Albariño',5,0,2,['lemon','grapefruit','white peach','orange blossom','acacia']],
 ['Broad aromatic white','white','Alsace','France','Gewürztraminer',2,0,5,['lychee','peach','orange peel','rose','ginger']]
];
const parents:Record<string,string[]>={'Chablis':['Burgundy'],'Northern Rhône':['Rhône Valley'],'Napa Valley':['California'],'Willamette Valley':['Oregon'],'Barossa Valley':['South Australia'],'Clare Valley':['South Australia']};
const value=(key:string,n:number)=>FIELDS[key].scale[n-1];
export const benchmarkReferences:WineReference[]=cases.map(([title,style,region,country,grape,acid,tannin,body,aromas],i)=>{
 const quality=i%3===0?'very-good':'good',vintage=2020+i%5;
 const grid:Record<string,string>={'app.clarity':'clear','app.intensity':style==='red'?(body>=4?'deep':'pale'):'pale','app.colour':style==='red'?'ruby':style==='rose'?'pink':'lemon','nose.condition':'clean','nose.intensity':body>=4?'pronounced':'medium+','nose.development':i===7?'developing':'youthful','pal.sweetness':i===14?'off-dry':'dry','pal.acidity':value('pal.acidity',acid),'pal.alcohol':body===5?'high':'medium','pal.body':value('pal.body',body),'pal.flavIntensity':'medium+','pal.finish':i%3===0?'long':'medium+','con.quality':quality,'con.readiness':style==='red'&&tannin>=4?'drink-or-age':'drink-now'};
 if(style==='red')grid['pal.tannin']=value('pal.tannin',tannin);
 if(i===2){grid['app.colour']='garnet';grid['pal.finish']='long';}
 if(i===7){grid['app.intensity']='medium';grid['app.colour']='garnet';}
 if(i===14)grid['pal.alcohol']='low';
 if(i===25)grid['pal.sweetness']='off-dry';
 const descriptors=aromas.map(term=>({term,stage:(['vanilla','cedar','toast','clove','chocolate'].includes(term)?'secondary':['leather','wet leaves','honey'].includes(term)?'tertiary':'primary') as 'primary'|'secondary'|'tertiary'}));
 return {id:'case-'+String(i+1).padStart(2,'0'),title,style,level:(i%3+1) as 1|2|3,regions:[region,...(parents[region]||[])],grapes:[grape],country,region,parentRegions:parents[region]||[],vintage,quality,grid,aromas:descriptors,flavors:aromas.slice(0,3),version:1,clue:`A hypothetical ${style==='rose'?'rosé':style} sample with ${aromas.slice(0,4).join(', ')}. Acidity is ${pretty(grid['pal.acidity'])}; body is ${pretty(grid['pal.body'])}${style==='red'?`; tannin is ${pretty(grid['pal.tannin'])}`:''}. The host places its vintage between ${vintage-1} and ${vintage+1}. Its balance and persistence support a ${pretty(quality)} quality call. Choose a plausible grape and origin, then compare with the authored answer. Other real wines can share these characteristics.`};
});
export const sources=[{label:'Tasting skills: WSET',url:'https://www.wsetglobal.com/knowledge-center/blog/2019/november/how-to-build-your-wine-tasting-skills/'},{label:'Training your palate: WSET',url:'https://www.wsetglobal.com/knowledge-center/blog/2026/how-to-train-your-palate'}];
