import {type WineReference,type WineStyle,pretty,FIELDS} from './academy-engine.ts';
export type Block={block:'prose'|'callout'|'prompt'|'term';text?:string;term?:string;gloss?:string};
export type AcademyLesson={id:string;type:'lesson'|'article';track:'structured'|'deductive'|'both';tier:1|2|3;title:string;summary:string;topics:string[];regions:string[];grapes:string[];access:'open';estMinutes:number;requires:string[];body:Block[];checks:{type:'mcq';stem:string;options:string[];answer:number;why:string}[];recall:{front:string;back:string}[];};
export const TRACK_LEVELS={structured:['Foundation','Working','Precision'],deductive:['Intro','Floor','Advanced']};
export const academyLessons:AcademyLesson[]=[
 {id:'systematic-method',type:'lesson',track:'both',tier:1,title:'A systematic approach to tasting',summary:'One order, four passes, one call at a time. The method Decant uses everywhere.',topics:['method','appearance','nose','palate','conclusions'],regions:[],grapes:[],access:'open',estMinutes:8,requires:[],body:[
 {block:'prose',text:'Tasting casually means noticing whatever shouts loudest. A systematic approach means visiting the same places in the same order every time, so what you notice is a property of the wine rather than of your mood. Decant uses four passes: look, smell, taste, conclude. Always that order, always the same fields, whether the glass is a Tuesday bottle or a blind sample.'},
 {block:'prose',text:'The order matters because each pass primes the next. Colour sets an expectation for weight and age. Aroma gives you words before your palate is tired. Structure is easiest to judge on a fresh mouth, so it comes before you chase flavour detail. Conclusions come last because they are the only step that is allowed to use everything.'},
 {block:'term',term:'Pass',gloss:'One trip through a single sense, finished before the next begins. Four passes make one complete note.'},
 {block:'prose',text:'Look. Hold the glass against something plain. Record clarity, how deep the colour is, and which colour it is. Tilt it and read the rim. That is all appearance owes you. Resist reading age or quality into colour before you have smelled anything.'},
 {block:'prose',text:'Smell. Swirl, then a short sniff rather than a long one; your nose adapts within seconds and a deep inhale tells you less, not more. Record condition first, since a faulty wine ends the exercise. Then intensity, then whether it smells youthful or developed, then the specific words. Five specific aromas is a good target. Raspberry, not red fruit.'},
 {block:'prose',text:'Taste. Take enough to coat the mouth. Make one call at a time and pause between them: sweetness, acidity, tannin if it is red, alcohol, body, flavour intensity, finish. Time the finish honestly, counting after you swallow or spit. Only then name the flavours, and expect them to overlap with what you smelled.'},
 {block:'prose',text:'Conclude. Two decisions: how good is it, and when should it be drunk. Both must rest on something you wrote in the first three passes. If you cannot point at the evidence, you are guessing, and a guess recorded as a conclusion quietly corrupts every note you compare it with later.'},
 {block:'callout',text:'Two rules that save the method from itself. Write each call before you say it out loud, because hearing your own opinion makes you defend it. And make a call even when you are unsure; an honest medium beats a blank, and the blank is what you cannot learn from.'},
 {block:'prose',text:'Use the same vocabulary every time. Decant fixes the scales for you: three positions for colour intensity and alcohol, five for acidity, tannin, body, aroma intensity, flavour intensity and finish. A range is not a call. Choose the closest single position and put your hesitation in the free text where it belongs.'},
 {block:'prose',text:'This is Decant’s own scheme, built for consistent practice. It is not any awarding body’s exam rubric, and matching a reference means agreeing with one authored case, not proving a universal truth about the wine.'},
 {block:'prompt',text:'Tonight I will taste ___ in this order. The pass I usually rush is ___. The call I most often leave blank is ___.'}],checks:[
 {type:'mcq',stem:'Why does structure come before naming flavours?',options:['Flavours are less important than structure','Your palate is freshest early, and structure is a physical sensation that fades with fatigue','Because flavours cannot be judged until you know the grape'],answer:1,why:'Structure is judged best on a fresh mouth. Chasing flavour detail first tires the palate and blurs the calls that matter most.'},
 {type:'mcq',stem:'You are unsure whether acidity is medium or medium (+). What does the method ask for?',options:['Leave it blank until you are certain','Record “medium to medium (+)”','Choose the closer single position and note the hesitation in your own words'],answer:2,why:'A range is not a decision. One call plus an honest note is what you can compare and learn from later.'},
 {type:'mcq',stem:'Which conclusion is built correctly?',options:['Very good, because the label is well regarded','Very good, because the finish was long and the fruit stayed clear through it','Very good, because it tastes expensive'],answer:1,why:'A conclusion has to point back at something you recorded in an earlier pass. The other two rest on information that never touched your palate.'}],recall:[
 {front:'What are the four passes, in order?',back:'Look, smell, taste, conclude.'},
 {front:'Why a short sniff rather than a long inhale?',back:'The nose adapts within seconds, so a long inhale returns less information, not more.'},
 {front:'What must every quality or readiness conclusion rest on?',back:'Something you actually recorded in the appearance, nose or palate pass.'},
 {front:'What does Decant ask you to do when a call is uncertain?',back:'Make the closest single call anyway and keep the uncertainty in the free text.'}]},
 {id:'structure-sensations',type:'lesson',track:'structured',tier:1,title:'Four sensations, four decisions',summary:'Separate freshness, grip, weight and persistence before reaching for a score.',topics:['acidity','tannin','body','finish'],regions:[],grapes:[],access:'open',estMinutes:5,requires:[],body:[
 {block:'prose',text:'Work through one sensation at a time. Acidity is mouth-watering freshness. Tannin is a drying grip. Body is the impression of weight. Finish is how long the flavour remains after the wine leaves your mouth. A strong aroma does not automatically mean a full body.'},
 {block:'callout',text:'Use a tasting you already planned; you do not need extra wine. Take a small sip, or spit, then make four separate calls. Water and a pause help you reset. It is fine to leave a personal slider unrecorded.'},
 {block:'term',term:'Structure',gloss:'The sensations that shape a wine in the mouth, considered separately from its flavours.'},
 {block:'prompt',text:'Freshness: ___. Drying grip: ___. Weight: ___. Flavour after the sip: ___.'}],checks:[{type:'mcq',stem:'A wine smells intense but feels light. Which call describes its body?',options:['Full, because its aroma is strong','Light, because body describes weight','High tannin, because it is intense'],answer:1,why:'Body describes the impression of weight. Aroma intensity is a separate observation.'}],recall:[{front:'Which sensation helps you recognise acidity?',back:'Mouth-watering freshness.'},{front:'How is tannin different from acidity?',back:'Tannin dries or grips; acidity makes the mouth water.'},{front:'What does finish describe?',back:'The persistence of flavour after the wine leaves your mouth.'}]},
 {id:'structure-scales',type:'lesson',track:'structured',tier:2,title:'Choose one place on the scale',summary:'Make a clear call and give each field the scale it actually uses.',topics:['scales','alcohol','appearance'],regions:[],grapes:[],access:'open',estMinutes:6,requires:['structure-sensations'],body:[
 {block:'prose',text:'In Decant practice, colour intensity has three choices: pale, medium and deep. Alcohol also has three: low, medium and high. Acidity, tannin, body, aroma intensity, flavour intensity and finish use five positions. A range is not a decision; choose the closest single position and keep your uncertainty in the free text.'},
 {block:'callout',text:'Try an authored practice case. Read the case note, complete the grid, and compare the result. Adjacent answers on five-position fields earn half credit. Three-position fields require the exact reference call.'},
 {block:'prose',text:'This scoring scheme belongs to Decant. It is practice in consistent observation, not an awarding body’s exam rubric. A real wine can vary with serving conditions; a practice reference is not a universal truth.'},
 {block:'prompt',text:'The field I hesitate over is ___. My single call is ___. My evidence is ___.'}],checks:[{type:'mcq',stem:'Which is a valid alcohol answer in this practice grid?',options:['Medium (+)','Medium to high','Medium'],answer:2,why:'Alcohol uses low, medium or high. A range or an extra intermediate step is not on this scale.'}],recall:[{front:'How many positions does Decant use for alcohol?',back:'Three: low, medium, high.'},{front:'What earns half credit on a five-position field?',back:'One position away from the authored reference.'}]},
 {id:'structure-descriptors',type:'lesson',track:'structured',tier:3,title:'Name the fruit, not the basket',summary:'Turn category words into specific observations and complete the conclusion.',topics:['descriptors','readiness','quality'],regions:[],grapes:[],access:'open',estMinutes:7,requires:['structure-scales'],body:[
 {block:'prose',text:'“Fruit” tells a reader less than “raspberry.” Start with a familiar, specific word. For these exercises, aim for five distinct aroma descriptors and three flavour descriptors. Repeating a word does not add a mark. A word outside the authored reference may still describe your real glass; the exercise only scores agreement with its reference.'},
 {block:'term',term:'Primary / secondary / tertiary',gloss:'A way to organise impressions associated with grape character, winemaking and development. The tag is feedback; descriptor marks assess the specific words.'},
 {block:'callout',text:'Write raspberry, vanilla and leather in three separate aroma rows. Tag each association, then explain your choices to yourself. Avoid treating a familiar descriptor as proof of a particular process.'},
 {block:'prose',text:'Finish with quality and a complete readiness decision. “Drink now” alone does not distinguish a wine that could develop from one intended for current enjoyment.'},
 {block:'prompt',text:'Specific aromas: ___. Flavours: ___. Ready now because ___. Further development seems ___.'}],checks:[{type:'mcq',stem:'Which entry is a specific descriptor rather than a category?',options:['Red fruit','Raspberry','Spice'],answer:1,why:'Raspberry names an individual aroma. Red fruit and spice group many possibilities together.'}],recall:[{front:'Why does “red fruit” not earn a descriptor mark here?',back:'It is a category. Name a specific fruit such as raspberry.'},{front:'Does an unmatched descriptor prove your own tasting is wrong?',back:'No. This exercise scores agreement with an authored case, not a universal sensory truth.'}]},
 {id:'deduction-observe',type:'lesson',track:'deductive',tier:1,title:'Observe before naming',summary:'Build a small set of possibilities from the evidence in front of you.',topics:['deduction','structure','evidence'],regions:[],grapes:[],access:'open',estMinutes:5,requires:[],body:[
 {block:'prose',text:'Delay the name of the wine. First record colour, freshness, grip, weight and a few specific aromas. Then propose two possibilities. Ask what fits each possibility and what does not. A confident first guess can make you overlook evidence that should change your mind.'},
 {block:'callout',text:'Use a written mystery case or have a friend conceal a bottle you already intended to taste. Give yourself three minutes. Say your observations aloud before making a call. The app does not record your microphone.'},
 {block:'prompt',text:'I observed ___. Possibility A: ___. Possibility B: ___. The evidence that separates them is ___.'}],checks:[{type:'mcq',stem:'What should come before a grape guess?',options:['A familiar producer name','A set of independent observations','The expected price'],answer:1,why:'Independent observations give you evidence to test, rather than a label to defend.'}],recall:[{front:'Why keep a second deduction possibility?',back:'It encourages you to test conflicting evidence rather than defend the first guess.'}]},
 {id:'deduction-chain',type:'lesson',track:'deductive',tier:2,title:'Make the reasoning audible',summary:'Connect observations to a grape and place, while keeping uncertainty visible.',topics:['deduction','region','country'],regions:['Bordeaux','Burgundy','Piedmont','Marlborough'],grapes:['Cabernet Sauvignon','Pinot Noir','Nebbiolo','Sauvignon Blanc'],access:'open',estMinutes:7,requires:['deduction-observe'],body:[
 {block:'prose',text:'Use a short chain: observation, possible explanation, conclusion. A drying grip is an observation. A particular grape is a hypothesis. The place on the label is a conclusion that needs more than one clue. Describe what would make you change that conclusion.'},
 {block:'callout',text:'Practice saying: “I favour ___ because ___ and ___. I considered ___, but ___ makes it less likely.” A concise chain is more useful than a long list of disconnected tasting words.'},
 {block:'prose',text:'Decant scores the final grape, region, country, vintage and quality calls separately. It saves your reasoning for review but does not pretend to grade spoken delivery, service or logic with a lookup table.'},
 {block:'prompt',text:'I favour ___ because ___ and ___. I considered ___, but ___. My confidence is ___.'}],checks:[{type:'mcq',stem:'What does the deterministic deduction score assess?',options:['Spoken confidence','Service performance','The five conclusion fields'],answer:2,why:'The reasoning is saved for reflection. Conclusion matching cannot assess a live service performance or the quality of a spoken argument.'}],recall:[{front:'What are the five scored deduction calls?',back:'Grape, region, country, vintage and quality.'}]},
 {id:'deduction-calibrate',type:'lesson',track:'deductive',tier:3,title:'Review the misses',summary:'Use repeat practice to spot a habit rather than chase a perfect score.',topics:['calibration','review','uncertainty'],regions:[],grapes:[],access:'open',estMinutes:6,requires:['deduction-chain'],body:[
 {block:'prose',text:'A useful review separates a sensory call from the conclusion built on it. If acidity was close but the region was wrong, work on the connection rather than changing every part of the note. Keep the original attempt so the next result has something honest to compare with.'},
 {block:'callout',text:'After ten full bottle-observation attempts against an exact bottle reference, read your calibration feedback. A persistent direction in your calls is worth exploring. Repeat the same case only to practise the habit; do not interpret memorising its answer as a better palate.'},
 {block:'prose',text:'Review a small number of recall cards each day. Use “Again” when the answer did not come back, and “Got it” when you recalled it before revealing it. Your saved cellar details can make the deck personal without inventing facts missing from a bottle record.'},
 {block:'prompt',text:'My recurring miss is ___. The evidence I should notice earlier is ___. Next time I will ___.'}],checks:[{type:'mcq',stem:'What is the most useful response to a repeated miss?',options:['Delete the old attempts','Identify the recurring decision and practise it','Only repeat the case until its answer is memorised'],answer:1,why:'Keeping earlier attempts helps you distinguish a genuine change in judgement from familiarity with one answer.'}],recall:[{front:'When does calibration begin?',back:'After ten full bottle-observation grids against exact bottle references, with ten valid calls for a field. Text exercises do not calibrate your palate.'}]}
];

// Original hypothetical cases. These are NOT measurements of named commercial wines.
const cases:[string,WineStyle,string,string,string,number,number,number,string[]][]=[
 ['Fresh red fruit','red','Burgundy','France','Pinot Noir',4,2,2,['raspberry','strawberry','cherry','violet','wet leaves']],
 ['Dark fruit and cedar','red','Bordeaux','France','Cabernet Sauvignon',4,4,4,['blackcurrant','plum','cedar','vanilla','leather']],
 ['Roses and firm grip','red','Piedmont','Italy','Nebbiolo',5,5,3,['rose','cherry','raspberry','leather','violet']],
 ['Pepper and dark berries','red','Northern Rhône','France','Syrah',4,4,4,['blackberry','blackcurrant','black pepper','violet','clove']],
 ['Ripe fruit and warmth','red','Barossa Valley','Australia','Shiraz',3,4,5,['blackberry','plum','black pepper','vanilla','chocolate']],
 ['Plush fruit and flowers','red','Mendoza','Argentina','Malbec',3,4,4,['plum','blackberry','violet','vanilla','clove']],
 ['Savoury red cherry','red','Tuscany','Italy','Sangiovese',5,4,3,['cherry','red plum','violet','leather','clove']],
 ['Developing red fruit','red','Rioja','Spain','Tempranillo',4,3,3,['strawberry','cherry','vanilla','leather','cedar']],
 ['Blackcurrant and weight','red','Napa Valley','United States','Cabernet Sauvignon',4,4,5,['blackcurrant','blackberry','vanilla','cedar','chocolate']],
 ['Delicate ripe cherry','red','Willamette Valley','United States','Pinot Noir',4,2,3,['cherry','raspberry','strawberry','violet','clove']],
 ['Citrus and a light frame','white','Chablis','France','Chardonnay',5,0,2,['lemon','green apple','pear','white peach','acacia']],
 ['Round orchard fruit','white','Burgundy','France','Chardonnay',4,0,4,['apple','white peach','lemon','vanilla','toast']],
 ['Tropical fruit and herbs','white','Marlborough','New Zealand','Sauvignon Blanc',5,0,2,['passion fruit','gooseberry','grapefruit','grass','green pepper']],
 ['Citrus and green notes','white','Loire Valley','France','Sauvignon Blanc',5,0,2,['lemon','grapefruit','gooseberry','grass','green apple']],
 ['Fragrant fruit and sweetness','white','Mosel','Germany','Riesling',5,0,2,['lime','green apple','white peach','honeysuckle','lemon']],
 ['Dry citrus and flowers','white','Clare Valley','Australia','Riesling',5,0,2,['lime','lemon','green apple','white peach','jasmine']],
 ['Orchard fruit and texture','white','Loire Valley','France','Chenin Blanc',5,0,3,['apple','pear','quince','honey','lemon']],
 ['Apricot and broad texture','white','Northern Rhône','France','Viognier',2,0,5,['apricot','peach','honeysuckle','orange blossom','pear']],
 ['Pale pink and citrus','rose','Provence','France','Grenache',4,0,2,['strawberry','raspberry','grapefruit','rose','white peach']],
 ['Pink fruit and fuller texture','rose','Rhône Valley','France','Grenache',3,0,4,['strawberry','raspberry','cherry','orange peel','rose']],
 ['Fresh berries and a light frame','red','Beaujolais','France','Gamay',4,1,2,['raspberry','cherry','strawberry','violet','peony']],
 ['Plum and a rounded frame','red','Bordeaux','France','Merlot',3,3,4,['plum','blackberry','cherry','cedar','leather']],
 ['Red fruit and a leafy edge','red','Loire Valley','France','Cabernet Franc',4,3,3,['raspberry','red plum','cherry','green pepper','graphite']],
 ['Fresh orchard fruit and spice','white','Niederösterreich','Austria','Grüner Veltliner',4,0,3,['green apple','pear','lemon','white pepper','acacia']],
 ['Citrus and stone fruit','white','Rías Baixas','Spain','Albariño',5,0,2,['lemon','grapefruit','white peach','orange blossom','acacia']],
 ['Broad aromatic white','white','Alsace','France','Gewürztraminer',2,0,5,['lychee','peach','orange peel','rose','ginger']]
];
const parents:Record<string,string[]>={'Chablis':['Burgundy'],'Northern Rhône':['Rhône Valley'],'Napa Valley':['California'],'Willamette Valley':['Oregon'],'Barossa Valley':['South Australia'],'Clare Valley':['South Australia']};
const value=(key:string,n:number)=>FIELDS[key].scale[n-1];
export const benchmarkReferences:WineReference[]=cases.map(([title,style,region,country,grape,acid,tannin,body,aromas],i)=>{
 const quality=i%3===0?'very-good':'good',vintage=2020+i%5;
 const grid:Record<string,string>={'app.clarity':'clear','app.intensity':style==='red'?(body>=4?'deep':'pale'):'pale','app.colour':style==='red'?'ruby':style==='rose'?'pink':'lemon','nose.condition':'clean','nose.intensity':body>=4?'pronounced':'medium+','nose.development':i===7?'developing':'youthful','pal.sweetness':i===14?'off-dry':'dry','pal.acidity':value('pal.acidity',acid),'pal.alcohol':body===5?'high':'medium','pal.body':value('pal.body',body),'pal.flavIntensity':'medium+','pal.finish':i%3===0?'long':'medium+','con.quality':quality,'con.readiness':style==='red'&&tannin>=4?'drink-or-age':'drink-now'};
 if(style==='red')grid['pal.tannin']=value('pal.tannin',tannin);
 if(i===2){grid['app.colour']='garnet';grid['pal.finish']='long';}
 if(i===7){grid['app.intensity']='medium';grid['app.colour']='garnet';}
 if(i===14)grid['pal.alcohol']='low';
 if(i===25)grid['pal.sweetness']='off-dry';
 const descriptors=aromas.map(term=>({term,stage:(['vanilla','cedar','toast','clove','chocolate'].includes(term)?'secondary':['leather','wet leaves','honey'].includes(term)?'tertiary':'primary') as 'primary'|'secondary'|'tertiary'}));
 return {id:'case-'+String(i+1).padStart(2,'0'),title,style,level:(i%3+1) as 1|2|3,regions:[region,...(parents[region]||[])],grapes:[grape],country,region,parentRegions:parents[region]||[],vintage,quality,grid,aromas:descriptors,flavours:aromas.slice(0,3),version:1,clue:`A hypothetical ${style==='rose'?'rosé':style} sample with ${aromas.slice(0,4).join(', ')}. Acidity is ${pretty(grid['pal.acidity'])}; body is ${pretty(grid['pal.body'])}${style==='red'?`; tannin is ${pretty(grid['pal.tannin'])}`:''}. The host places its vintage between ${vintage-1} and ${vintage+1}. Its balance and persistence support a ${pretty(quality)} quality call. Choose a plausible grape and origin, then compare with the authored answer. Other real wines can share these characteristics.`};
});
export const sources=[{label:'Tasting skills: WSET',url:'https://www.wsetglobal.com/knowledge-centre/blog/2019/november/how-to-build-your-wine-tasting-skills/'},{label:'Training your palate: WSET',url:'https://www.wsetglobal.com/knowledge-centre/blog/2026/how-to-train-your-palate'}];
