export type Lesson={title:string;body:string;question?:string;options?:string[];answer?:number};
export type Education={id:string;kind:'article'|'course';title:string;summary:string;category:string;tier:number;status:string;body:Lesson[];updated_at?:string;locked?:boolean;lessonCount?:number};
export const initialContent:Education[]=[
{id:'wine-foundations',kind:'course',title:'Find your palate',summary:'A practical introduction to tasting, without the intimidating vocabulary.',category:'Foundations',tier:0,status:'published',body:[
{title:'Start with what you notice',body:'You do not need a perfect vocabulary to keep a useful tasting note. Start with a quiet moment and write three observations: what you smell, how the wine feels, and whether you enjoy it.\n\nTry this: choose a familiar aroma, such as lemon peel or fresh berries. Smell it first, then smell your glass. The point is to make your own associations, not to find the correct answer.\n\nYour notebook prompt: “This reminds me of …” Keep your first impression. Taste preferences can change with food, temperature, and company.',question:'What is the most useful starting point for a personal tasting note?',options:['An impressive technical term','An honest observation in your own words','The price of the bottle'],answer:1},
{title:'Separate acidity from tannin',body:'Acidity makes your mouth water. Tannin creates a drying sensation around the gums. These are different feelings, even when both are present.\n\nTake a small sip. After swallowing or spitting, notice whether your mouth waters or feels dry. Describe each sensation separately: low, medium, or high is enough.\n\nPractice prompt: compare your notes from two wines on different occasions. You do not need to open extra bottles to learn.\n\nFurther reading: https://www.wsetglobal.com/knowledge-centre/blog/2026/the-secret-language-of-wine-what-is-mouthfeel',question:'Which sensation is most associated with tannin?',options:['Mouth-watering freshness','A drying feeling on the gums','Bubbles'],answer:1},
{title:'Build a note you will use again',body:'A useful note helps future you choose a bottle. Record the producer, wine name, vintage if shown, date, and one or two observations. Finish with the occasion and a simple decision: would you drink it again?\n\nTry this template: “I noticed ___. With food it felt ___. I would open this again for ___.”\n\nLeave room for uncertainty. “Maybe citrus” is more useful than copying a description that does not match your experience. Revisit a note the next time you encounter the wine.',question:'Which detail makes a tasting note useful later?',options:['A personal occasion or food match','Only the label colour','Someone else’s score'],answer:0}]},
{id:'pairing-principles',kind:'course',title:'A seat at the table',summary:'Understand how food changes wine, then put the idea to work at dinner.',category:'Food & wine',tier:2,status:'published',body:[
{title:'Taste the food, then the wine',body:'Food can change how a wine tastes. A pairing is an experience, not a rigid rule. Begin with the dominant part of the dish: its sauce, sweetness, salt, acidity, or chilli.\n\nTry a small taste of wine on its own, then after a bite of food. Note what changed.\n\nFurther reading: https://www.wsetglobal.com/knowledge-centre/blog/2023/july/13/four-rules-to-masterful-food-and-wine-pairing/'},
{title:'Work with sweetness and heat',body:'Sweet food can make a dry wine seem less fruity and more bitter. With chilli, alcohol can intensify the sensation of heat. These are useful starting points, not promises about everyone’s preferences.\n\nAt your next dinner, compare the wine before and after a small bite. If the combination feels harsh, try water and enjoy the food without forcing a match.\n\nFurther reading: https://www.wsetglobal.com/knowledge-centre/blog/2026/how-to-pair-drinks-with-spice'},
{title:'Make your own pairing map',body:'Create three columns in your tasting note: dish, wine, and what changed. Record the sauce and seasoning as well as the main ingredient.\n\nAfter several meals, look for combinations you enjoyed. Your own record will be more useful than a universal pairing chart. Finish by saving a pairing you would serve to friends.'}]},
{id:'cellar-intention',kind:'article',title:'Build a cellar with intention',summary:'Start with the occasions you actually have, and let the collection grow from there.',category:'Cellar craft',tier:1,status:'published',body:[{title:'A collection that fits your life',body:'Before buying another bottle, list three occasions you want your cellar to serve: a weeknight meal, a dinner with friends, or a celebration. Assign the bottles you already own to those occasions.\n\nKeep the useful details together: quantity, storage location, purchase price, and your own planned drinking window. Treat any drinking window as an estimate. Storage history and bottle condition matter.\n\nReview the collection regularly. Move forgotten bottles into view and make a plan for them. A thoughtful cellar is one you enjoy using.'}]},
{id:'better-notes',kind:'article',title:'The three-line tasting note',summary:'A small habit that makes every bottle easier to remember.',category:'Foundations',tier:0,status:'published',body:[{title:'Less ceremony, more memory',body:'Line one: what did you notice? Use a familiar aroma, a texture, or a short phrase.\n\nLine two: where were you, and what was on the table? Context is part of the memory.\n\nLine three: would you choose it again? Say why.\n\nTry it in your tasting journal today. A short note written while the experience is fresh is better than a detailed note you never get around to writing.'}]},
{id:'hosting-flight',kind:'course',title:'The thoughtful host',summary:'Plan an inviting tasting with a clear theme, good notes, and room for conversation.',category:'Hosting',tier:3,status:'published',body:[{title:'Choose one question',body:'A useful tasting starts with a question. How do two styles of the same grape differ? Which bottle works best with tonight’s food? Keep the theme narrow enough that everyone can take part.\n\nTwo or three wines are plenty for a first comparison. Offer water, food, and an equally considered alcohol-free option. Participation should never depend on drinking.'},{title:'Prepare the table',body:'Label glasses or tasting positions so guests can follow the comparison. Keep a short note sheet with space for first impressions and favourites. Offer small pours, and make spitting or leaving wine unfinished feel normal.\n\nThe hosting planner estimates bottle volume from guest count and pour size. It is a supply estimate, not a target for anyone to drink.'},{title:'Let people disagree',body:'Give everyone time to make a first note before discussing the wines. Ask what they noticed, then what they enjoyed. Avoid turning the conversation into a test.\n\nSave the evening’s plan and your favourite pairing in your notebook. Next time, use what you learned to choose a new question.'}]}];
export const plans=[{id:1,name:'Cellar',price:5,tag:'For the everyday enthusiast',features:['Your private cellar and tasting journal','All education articles','Pairing guide and saved hosting plans']},{id:2,name:'Explorer',price:10,tag:'For the endlessly curious',features:['Everything in Cellar','Foundations and food & wine courses','Lesson progress and knowledge checks']},{id:3,name:'Connoisseur',price:15,tag:'For the considered wine life',features:['Everything in Explorer','Every course, including hosting','Access to future top-tier education']}];
