import {FIELDS,pretty,type WineReference,type Score} from './academy-engine.ts';
export const REVEAL_CEILINGS={1:100,2:80,3:60} as const;
export type Drill={id:string;referenceId:string;fruit:string[];nonFruit:string[];candidates:string[];answer:string;discriminator:{question:string;options:string[];answer:number;why:string}};
// Individually edited confusion sets. The first explanation is the key before display rotation.
// These are comparative questions about a fictional sample, never claims of unique identification.
const editorial:[string[],string,string,string,string][]=[
 [['Pinot Noir','Gamay','Nebbiolo'],'Which structural clue most weakens Nebbiolo?', 'The modest tannin despite bright acidity.', 'The bright acidity despite a light frame.', 'The long finish despite pale colour.'],
 [['Cabernet Sauvignon','Merlot','Syrah'],'With Syrah still structurally plausible, which further clue would most favour Cabernet Sauvignon?', 'A blackcurrant-led profile with a cedar association.', 'A blackberry-led profile with a pepper association.', 'A violet association accompanying dark fruit.'],
 [['Nebbiolo','Sangiovese','aged Pinot Noir'],'What most favours Nebbiolo over Sangiovese in this case?', 'Tannin at the top of the scale despite a medium frame; high acid alone does not separate them.', 'The medium frame and high acidity; tannin adds little to the comparison.', 'The pale colour and medium alcohol; both make Sangiovese structurally implausible.'],
 [['Syrah','Cabernet Sauvignon','Merlot'],'With Cabernet Sauvignon still structurally plausible, which further clue would most favour Syrah?', 'Pepper accompanying dark berries.', 'Cedar accompanying blackcurrant.', 'Vanilla accompanying dark berries.'],
 [['Shiraz','Cabernet Sauvignon','Zinfandel'],'Which observation most weakens a cooler, leaner interpretation?', 'High alcohol together with full body and only medium acidity.', 'Firm tannin together with a persistent finish.', 'Deep colour together with medium acidity alone.'],
 [['Malbec','Merlot','Shiraz'],'Which observation carries least weight against the Merlot alternative?', 'Deep colour: extraction and ripeness can give both depth.', 'The combination of firm tannin with substantial body.', 'The balance between moderate acidity and a firm grip.'],
 [['Sangiovese','Nebbiolo','Tempranillo'],'What most favours this case over the Nebbiolo benchmark?', 'High acidity remains, but tannin is a step lower rather than equally high.', 'Tannin exceeds acidity, suggesting a more extracted style.', 'Low alcohol explains the tannin more convincingly than variety.'],
 [['Tempranillo','Sangiovese','Merlot'],'Which comparison most weakens a young, firmly tannic Sangiovese?', 'Tannin is moderate rather than firm, with acidity below the top of the scale.', 'Acidity reaches the top of the scale while tannin stays firm.', 'The full body and high alcohol outweigh its red-fruit character.'],
 [['Cabernet Sauvignon','Shiraz','Merlot'],'Which combination supports a riper interpretation?', 'Full body and high alcohol, considered alongside retained acidity.', 'Deep colour and a persistent finish, without reference to alcohol.', 'Firm tannin and bright acidity, without reference to body.'],
 [['Pinot Noir','Gamay','Cabernet Franc'],'What most weakens a firmly extracted Cabernet Franc?', 'The modest tannin; acidity and medium body alone would not exclude it.', 'The medium body; Pinot Noir must always be light.', 'The bright acidity; Cabernet Franc cannot retain freshness.'],
 [['Chardonnay','Chenin Blanc','Sauvignon Blanc'],'Which further clue would most strengthen Sauvignon Blanc over this Chardonnay call?', 'A clear leafy or grassy note beside the citrus.', 'Orchard fruit beside the citrus.', 'A floral impression beside the citrus.'],
 [['Chardonnay','Chenin Blanc','Pinot Gris'],'Which observation best supports the broad Chardonnay interpretation rather than a lean white?', 'The substantial body, with acidity still retained.', 'The pale colour, with medium alcohol retained.', 'The citrus fruit, with a persistent finish.'],
 [['Sauvignon Blanc','Riesling','Albariño'],'Which later clue best separates this Sauvignon Blanc case from Riesling?', 'Gooseberry and passion fruit with a grassy edge.', 'Citrus with a floral edge.', 'Citrus with green apple and high acidity.'],
 [['Sauvignon Blanc','Riesling','Chenin Blanc'],'Which later clue most weakens the Riesling alternative?', 'The grassy and gooseberry combination.', 'The lemon and grapefruit combination.', 'Green apple with high acidity.'],
 [['Riesling','Chenin Blanc','Pinot Gris'],'Which pair of structural observations should be considered together?', 'Low alcohol and slight sweetness, while the acidity remains high.', 'Full body and high alcohol, while the acidity remains high.', 'Low acidity and slight sweetness, while the body remains light.'],
 [['Riesling','Sauvignon Blanc','Albariño'],'Which later observation would most strengthen Sauvignon Blanc over Riesling?', 'A pronounced grassy edge to the citrus fruit.', 'A pronounced floral edge to the citrus fruit.', 'A pronounced lime edge to the citrus fruit.'],
 [['Chenin Blanc','Riesling','Chardonnay'],'Which comparison deserves most attention?', 'The medium weight with high acidity; neither field alone settles the variety.', 'The high alcohol with low acidity; together they settle the variety.', 'The lightest body with low alcohol; together they settle the variety.'],
 [['Viognier','Gewürztraminer','Pinot Gris'],'What would most strengthen Gewürztraminer over Viognier after this shared broad structure?', 'Lychee and rose rather than an apricot-led profile.', 'Peach and blossom rather than a citrus-led profile.', 'Ripe pear rather than green apple.'],
 [['Grenache-led rosé','Pinot Noir rosé','Syrah-led rosé'],'Which observation is least useful for separating these rosé blends?', 'Pale colour, because extraction changes it substantially.', 'The balance of alcohol and body.', 'The balance of acidity and weight.'],
 [['Grenache-led rosé','Syrah-led rosé','Sangiovese rosé'],'What separates this from a lean, sharply acidic rosé?', 'Substantial body and medium acidity considered together.', 'Pale colour and medium alcohol considered together.', 'Red fruit alone, regardless of the mouthfeel.'],
 [['Gamay','Pinot Noir','Cabernet Franc'],'Which first-round observation most weakens firmly extracted Cabernet Franc?', 'Low tannin paired with a light frame.', 'Bright acidity paired with medium alcohol.', 'Pale colour paired with a persistent finish.'],
 [['Merlot','Cabernet Sauvignon','Malbec'],'Which comparison most weakens a very firm Cabernet Sauvignon?', 'Moderate tannin relative to the substantial body.', 'Substantial body relative to the medium alcohol.', 'Deep colour relative to the persistent finish.'],
 [['Cabernet Franc','Sangiovese','Merlot'],'Which later clue most supports Cabernet Franc over Sangiovese?', 'A leafy green-pepper edge beside the red fruit.', 'A red-cherry edge beside fresh acidity.', 'A savoury edge beside moderate weight.'],
 [['Grüner Veltliner','Sauvignon Blanc','Chenin Blanc'],'Which later clue most supports Grüner Veltliner in this set?', 'White pepper accompanying orchard fruit.', 'Grass accompanying citrus fruit.', 'Honey and quince accompanying orchard fruit.'],
 [['Albariño','Riesling','Sauvignon Blanc'],'Which further clue would most strengthen Sauvignon Blanc over Albariño?', 'A grassy edge beside the citrus.', 'A blossom note beside white peach.', 'A citrus note beside stone fruit.'],
 [['Gewürztraminer','Viognier','Pinot Gris'],'Which observation makes high-acid Riesling a weaker alternative?', 'Lower acidity together with full body and high alcohol.', 'Slight sweetness together with a persistent finish.', 'Pale colour together with pronounced aromas.']
];
const fruitWords=new Set(['raspberry','strawberry','cherry','blackcurrant','plum','blackberry','red plum','lemon','green apple','pear','white peach','apple','passion fruit','gooseberry','grapefruit','lime','quince','apricot','peach','orange peel','lychee']);
export function hasDrill(ref:WineReference){return /^case-\d{2}$/.test(ref.id)&&!!editorial[Number(ref.id.slice(5))-1]&&!ref.lwin;}
export function drillFor(ref:WineReference):Drill{
 if(!hasDrill(ref))throw new Error('This reference needs an authored reveal ladder and confusion set before it can be a daily drill.');
 const index=Number(ref.id.slice(5))-1,[base,question,...explanations]=editorial[index];
 const shift=index%3,candidates=[...base.slice(shift),...base.slice(0,shift)];
 const answerIndex=(index+1)%3,options=[...explanations];[options[0],options[answerIndex]]=[options[answerIndex],options[0]];
 return {id:'drill-'+ref.id,referenceId:ref.id,fruit:ref.aromas.filter(a=>fruitWords.has(a.term)).map(a=>a.term),nonFruit:ref.aromas.filter(a=>!fruitWords.has(a.term)).map(a=>a.term),candidates,answer:base[0],discriminator:{question,options,answer:answerIndex,why:explanations[0]+' These are authored benchmark tendencies, not a unique identification of every real wine.'}};
}
export function structureClue(ref:WineReference){return [`${pretty(String(ref.grid['app.intensity']))} ${pretty(String(ref.grid['app.colour']))}`, ...['pal.sweetness','pal.acidity','pal.tannin','pal.alcohol','pal.body','pal.finish'].filter(k=>k!=='pal.tannin'||ref.style==='red').map(k=>`${FIELDS[k].label}: ${pretty(String(ref.grid[k]))}`)].join(' · ')}
export function scoreDrill(answers:any,ref:WineReference):Score{
 const drill=drillFor(ref),round=Number(answers.round);
 if(![1,2,3].includes(round)||!drill.candidates.includes(answers.choice)||!['Old World','New World','Uncertain'].includes(answers.world)||!['Cool / moderate','Warm','Uncertain'].includes(answers.climate)||!Number.isInteger(answers.discriminator)||answers.discriminator<0||answers.discriminator>=3)throw new Error('Commit a hypothesis, choose a candidate and answer the discriminator.');
 const ceiling=REVEAL_CEILINGS[round as 1|2|3];
 const fields=[['candidate',75,answers.choice,drill.answer],['discriminator',25,answers.discriminator,drill.discriminator.answer]] as const;
 const byField=Object.fromEntries(fields.map(([key,max,given,reference])=>[key,{given:key==='discriminator'?drill.discriminator.options[Number(given)]:given,reference:key==='discriminator'?drill.discriminator.options[Number(reference)]:reference,max,marks:given===reference?max*ceiling/100:0,message:given===reference?'':key==='discriminator'?drill.discriminator.why:`The authored candidate is ${reference}.`}]));
 const marks=Object.values(byField).reduce((n,r)=>n+r.marks,0);
 return {marks,max:100,percent:Math.round(marks),byField,messages:[`Called in round ${round}. Available score: ${ceiling}/100.`, `Authored candidate: ${drill.answer}. ${answers.choice===drill.answer?'Your call matched.':'Your call did not match.'}`, `Your initial hypothesis: ${answers.world}; ${answers.climate}. Retained for reflection, not scored as geography established by structure.`,drill.discriminator.why,...Object.values(byField).map(r=>r.message).filter(Boolean)]};
}
