import {pairingSources,normalizeText,matchesTerm} from './food-pairings.ts';
export type Dish={name:string;why:string};
export type WineProfile={label:string;style:string;keywords:string[];intro:string;dishes:Dish[];tip?:string};
export type WineMatch={label:string;style:string;intro:string;dishes:Dish[];tip?:string;keywords:string[];exact:boolean};
const d=(name:string,why:string):Dish=>({name,why});
const wineProfiles:WineProfile[]=[
{label:'Cabernet Sauvignon',style:'Red',keywords:['cabernet','cabernet sauvignon','bordeaux','claret','meritage'],intro:'Firm tannin and dark fruit, often with oak. It shows best beside protein and fat, and can taste hard next to heat or sharp acidity.',tip:'Tannin softens against fat and protein. Chilli heat and vinegar push it the other way.',dishes:[d('Grilled steak','Fat and protein soften tannin, which is why this is the reference pairing.'),d('Roast lamb with rosemary','Savoury herbs and rich meat meet the wine’s structure rather than fighting it.'),d('Aged cheddar or gouda','Salt and fat in a hard cheese give tannin something to hold onto.'),d('Braised short ribs','Slow-cooked beef and dark fruit sit comfortably together.')]},
{label:'Merlot',style:'Red',keywords:['merlot','pomerol','saint emilion','st emilion'],intro:'Softer tannin and plummy fruit. One of the more forgiving reds when the table is not all steak.',dishes:[d('Roast chicken with gravy','Gentle tannin suits poultry that a bigger red would flatten.'),d('Pork tenderloin','Mild meat and ripe fruit meet in the middle.'),d('Mushroom and sausage pizza','Enough fruit for tomato, enough softness for cheese.'),d('Lentil or bean stew','Earthy, savoury cooking is a good home for plummy reds.')]},
{label:'Pinot Noir',style:'Red',keywords:['pinot noir','red burgundy','bourgogne rouge','spatburgunder','gevrey','volnay'],intro:'Light tannin, red fruit and a savoury edge. It works with food that a heavier red would bury.',tip:'One of the few reds that is comfortable with fish.',dishes:[d('Roast duck','Red fruit and gentle structure follow the meat without covering it.'),d('Grilled salmon','Low tannin means an oily fish stays clean rather than turning metallic.'),d('Mushroom risotto','Earthy flavors on both sides echo each other.'),d('Roast turkey','A safe center-of-the-table red when the sides vary wildly.')]},
{label:'Syrah or Shiraz',style:'Red',keywords:['syrah','shiraz','hermitage','cornas','cote rotie','crozes'],intro:'Dark fruit with pepper and smoke. Cooler-climate bottles lean savoury, warmer ones lean ripe and sweet-fruited.',dishes:[d('Peppered steak','The wine’s own pepper note meets the crust on the meat.'),d('Lamb shoulder','Rich, fatty meat is a natural fit for the structure.'),d('Barbecue ribs','Smoke on the plate and smoke in the glass, especially with riper styles.'),d('Merguez or spiced sausage','Savoury spice suits the peppery side of the grape.')]},
{label:'Malbec',style:'Red',keywords:['malbec','cahors'],intro:'Plush dark fruit with firm but rounded structure. Built for the grill.',dishes:[d('Burgers','Fruit and structure hold up to beef, cheese and a bun.'),d('Steak with chimichurri','Herb and garlic sharpen the fruit rather than clashing with it.'),d('Empanadas','Savoury pastry and beef filling are a classic local match.'),d('Barbecued short ribs','Char and fat meet plush fruit.')]},
{label:'Sangiovese',style:'Red',keywords:['sangiovese','chianti','brunello','montalcino'],intro:'Bright acidity, savoury herbs and firm tannin. Built by a food culture, and it shows.',tip:'The acidity is the point: it is what lets it sit next to tomato.',dishes:[d('Tomato pasta','Acidity in the wine meets acidity in the sauce so neither tastes flat.'),d('Pizza margherita','Savoury, bright and unfussy on both sides.'),d('Lasagna','Enough structure for meat and cheese, enough freshness for the sauce.'),d('Aged pecorino','Salt and nuttiness suit the savoury edge.')]},
{label:'Nebbiolo',style:'Red',keywords:['nebbiolo','barolo','barbaresco','gattinara'],intro:'Pale in the glass, firm in the mouth. High tannin and acidity with tar, rose and dried cherry.',dishes:[d('Braised beef','Long-cooked meat and gelatinous sauce are the traditional answer to the tannin.'),d('Truffle pasta','Aromatic, savoury and earthy on both sides.'),d('Mushroom risotto','Earthy depth without the weight of red meat.'),d('Aged hard cheese','Salt and fat take the edge off a young, grippy bottle.')]},
{label:'Barbera',style:'Red',keywords:['barbera'],intro:'Juicy fruit and high acidity with very little tannin. An easy weeknight red.',dishes:[d('Tomato pasta','High acidity keeps up with the sauce.'),d('Salumi and cured meats','Fruit and freshness cut through salt and fat.'),d('Pizza','Low tannin means it does not fight the cheese.'),d('Roast chicken','Light enough for poultry, savoury enough to be interesting.')]},
{label:'Tempranillo',style:'Red',keywords:['tempranillo','rioja','ribera del duero','toro'],intro:'Red fruit, leather and often American oak giving vanilla and dill. Savoury more than sweet.',dishes:[d('Roast lamb','The traditional pairing in its home region, and hard to improve on.'),d('Jamón and manchego','Salt, fat and nuttiness suit the oak-driven style.'),d('Chorizo and grilled peppers','Smoked paprika meets the savoury side of the wine.'),d('Grilled pork','Enough weight for the meat without overwhelming it.')]},
{label:'Grenache or Garnacha',style:'Red',keywords:['grenache','garnacha','chateauneuf','cotes du rhone','priorat','gsm','gigondas'],intro:'Ripe red fruit, warming alcohol and soft tannin, often with a herbal, scrubby note.',dishes:[d('Roast lamb with herbs','Herbs on the plate pick up the wine’s own garrigue character.'),d('Sausage and white beans','Hearty, savoury cooking suits the ripe fruit.'),d('Spiced tagine','Warm spice and dried fruit echo the wine, as long as heat stays moderate.'),d('Barbecue','Fruit-forward reds handle smoke and sweet glaze.')]},
{label:'Zinfandel',style:'Red',keywords:['zinfandel','primitivo'],intro:'Jammy fruit, often high alcohol, sometimes a touch of sweetness. Loud food is welcome.',tip:'Watch the alcohol with chilli heat; it makes the burn stronger.',dishes:[d('Barbecue ribs','Sweet, smoky glaze meets jammy fruit.'),d('Pepperoni pizza','Enough fruit and weight for spiced, fatty toppings.'),d('Burgers','A ripe, generous red for a ripe, generous sandwich.'),d('Sticky glazed pork','Sweetness on the plate needs fruit in the glass.')]},
{label:'Gamay or Beaujolais',style:'Red',keywords:['gamay','beaujolais','morgon','fleurie','brouilly'],intro:'Light body, low tannin, bright red fruit. Serve it slightly chilled and it goes almost anywhere.',dishes:[d('Charcuterie','Freshness cuts salt and fat without any tannic weight.'),d('Roast chicken','A light red that flatters poultry rather than dominating it.'),d('Thanksgiving turkey and sides','Flexible enough for a table with a dozen competing flavors.'),d('Goat cheese','Acidity on both sides keeps it fresh.')]},
{label:'Cabernet Franc',style:'Red',keywords:['cabernet franc','chinon','bourgueil','saumur'],intro:'Red fruit with a green, leafy, peppery streak. Savoury and medium-weight.',dishes:[d('Roast peppers and vegetables','The wine’s herbal edge matches rather than clashes.'),d('Herb-roasted chicken','Savoury herbs meet the leafy note in the wine.'),d('Lentils and sausage','Earthy and savoury on both sides.'),d('Goat cheese','A regional pairing that works on acidity and freshness.')]},
{label:'Chardonnay',style:'White',keywords:['chardonnay','white burgundy','bourgogne blanc','meursault','pouilly fuisse','montrachet'],intro:'Ranges from lean and mineral to rich, oaky and buttery. Match the weight of the bottle to the weight of the dish.',tip:'Oak and lees give texture; unoaked bottles behave more like Chablis below.',dishes:[d('Roast chicken','The classic: enough texture for the skin, enough freshness for the meat.'),d('Lobster or crab with butter','Rich seafood and a richer white move at the same pace.'),d('Creamy pasta','Texture meets texture, while acidity stops it from going heavy.'),d('Seared scallops','Sweet shellfish and a touch of oak are a long-standing pairing.')]},
{label:'Chablis',style:'White',keywords:['chablis','petit chablis'],intro:'Chardonnay without the weight: lean, taut and often saline, usually with little or no oak.',dishes:[d('Oysters','The reference pairing, built on salinity and acidity.'),d('Raw and steamed shellfish','Nothing in the wine gets in the way of delicate seafood.'),d('Sushi and sashimi','Clean and dry, which is what raw fish asks for.'),d('Goat cheese','Chalky, fresh cheese meets a chalky, fresh wine.')]},
{label:'Sauvignon Blanc',style:'White',keywords:['sauvignon blanc','sancerre','pouilly fume','sauvignon'],intro:'High acidity with citrus, grass and green herbs. It sharpens fresh flavors and handles vinegar better than most wines.',dishes:[d('Goat cheese','The regional classic, and one of the most reliable pairings in wine.'),d('Green salad with vinaigrette','One of the few wines that survives a sharp dressing.'),d('Asparagus and green vegetables','A notoriously difficult ingredient that this grape handles.'),d('Ceviche','Citrus and acidity on both sides.')]},
{label:'Riesling',style:'White',keywords:['riesling','kabinett','spatlese','mosel','rheingau'],intro:'High acidity, low to moderate alcohol, and anything from bone dry to very sweet. Check the label before you plan the plate.',tip:'For chilli heat, off-dry is the safer choice. Sweetness cools the burn; alcohol raises it.',dishes:[d('Thai or Vietnamese curry','A little sweetness softens heat while acidity keeps the dish bright.'),d('Sichuan cooking','Low alcohol is the key: it keeps the chilli from flaring.'),d('Pork schnitzel','Acidity cuts a fried cutlet cleanly.'),d('Smoked fish','Sweet-and-sharp contrast works well against smoke and salt.')]},
{label:'Pinot Grigio or Pinot Gris',style:'White',keywords:['pinot grigio','pinot gris'],intro:'Italian styles tend to be light and crisp; Alsace styles are richer and sometimes off-dry. Both stay easygoing.',dishes:[d('Simply cooked white fish','Light and clean, so nothing competes with the fish.'),d('Prosciutto and melon','Salt, sweetness and a wine that stays out of the way.'),d('Fried calamari','Freshness cuts the batter.'),d('Light summer salads','An undemanding wine for undemanding food.')]},
{label:'Albariño',style:'White',keywords:['albarino','rias baixas','alvarinho'],intro:'Citrus, stone fruit and a saline finish. Coastal wine for coastal food.',dishes:[d('Garlic prawns','Bright acidity and a saline edge suit shellfish and garlic.'),d('Grilled sardines','Oily fish needs acidity, and this has plenty.'),d('Steamed mussels','Saline wine, saline broth.'),d('Ceviche','Citrus on both sides of the pairing.')]},
{label:'Chenin Blanc',style:'White',keywords:['chenin','vouvray','savennieres','steen','montlouis'],intro:'Apple, quince and honey with high acidity, made dry through to sweet. One of the most versatile whites at the table.',dishes:[d('Pork with apple','Orchard fruit in the glass meets orchard fruit on the plate.'),d('Creamy risotto','Acidity and texture together handle a rich dish.'),d('Thai salads','Off-dry bottles cope with lime, herbs and a little heat.'),d('Soft washed-rind cheese','Honeyed weight stands up to a pungent cheese.')]},
{label:'Grüner Veltliner',style:'White',keywords:['gruner veltliner','gruner','veltliner'],intro:'Citrus, white pepper and a savoury, vegetal streak. Good at the things that usually break wine pairings.',dishes:[d('Asparagus','One of the few wines that genuinely enjoys it.'),d('Wiener schnitzel','Acidity and a squeeze of lemon, effectively in liquid form.'),d('Herby salads and green vegetables','The wine’s vegetal note matches instead of clashing.'),d('Dumplings','Savoury, peppery and light enough not to overwhelm.')]},
{label:'Gewürztraminer',style:'White',keywords:['gewurztraminer','traminer'],intro:'Loudly aromatic: lychee, rose and ginger, with low acidity and often a touch of sweetness.',dishes:[d('Aromatic curry','Intensity on both sides, and sweetness to handle spice.'),d('Munster or other pungent cheese','The Alsace pairing, where perfume meets funk.'),d('Ginger and five-spice cooking','The wine’s own spice notes echo the dish.'),d('Duck with orange','Rich meat and a perfumed, slightly sweet white.')]},
{label:'Viognier',style:'White',keywords:['viognier','condrieu'],intro:'Apricot and peach, full body, low acidity and a perfumed nose. Rich without being sweet.',dishes:[d('Apricot-glazed chicken','Stone fruit on the plate mirrors stone fruit in the glass.'),d('Mild curry','Aromatic weight handles spice as long as heat stays gentle.'),d('Seared scallops','Sweet shellfish suits the round texture.'),d('Roast squash','Sweet, soft vegetables meet a soft, perfumed white.')]},
{label:'Muscadet',style:'White',keywords:['muscadet','melon de bourgogne','sevre et maine'],intro:'Bone dry, light and saline, sometimes with a yeasty texture from lees aging. It exists for shellfish.',dishes:[d('Oysters','The defining pairing: salt, brine and acidity.'),d('Steamed mussels','Light enough that the broth leads.'),d('Fried whitebait or fish and chips','Clean acidity resets the palate between bites.'),d('Raw bar platters','Neutral and dry, so nothing interferes.')]},
{label:'Dry rosé',style:'Rosé',keywords:['rose','rosado','provence','bandol','rosato'],intro:'Red-grape fruit with white-wine freshness. It bridges dishes where the table cannot agree on red or white.',tip:'Confirm it is dry. Sweeter pink wines behave very differently at the table.',dishes:[d('Salade niçoise','Summer food and the wine that grew up beside it.'),d('Grilled prawns','Fresh and fruity without the weight of a red.'),d('Charcuterie','Cuts salt and fat while keeping some red-fruit character.'),d('Tacos','Flexible enough for spice, lime, and whatever the filling is.')]},
{label:'Champagne and traditional-method sparkling',style:'Sparkling',keywords:['champagne','cremant','cava','traditional method','blanc de blancs','blanc de noirs','franciacorta'],intro:'High acidity, bubbles and a bready, yeasty depth. One of the most flexible things you can put on a table.',tip:'Bubbles and acidity scrub fat and salt, which is why it works with fried food.',dishes:[d('Fried chicken','The famous pairing, and it earns its reputation on texture alone.'),d('Potato chips','Salt and crunch against acidity and bubbles.'),d('Oysters','Briny, clean and classic.'),d('Popcorn','The wine’s toasty note meets the buttered corn.')]},
{label:'Prosecco',style:'Sparkling',keywords:['prosecco','glera','asolo','valdobbiadene'],intro:'Softer bubbles and pear-and-white-flower fruit, usually off-dry rather than bone dry. Lighter in body than Champagne.',dishes:[d('Prosciutto and melon','Salt, sweetness and gentle fizz.'),d('Light appetisers','Easy, fruity and undemanding before a meal.'),d('Fruit desserts','A touch of sweetness keeps it in balance.'),d('Brunch','Low alcohol and soft fruit suit eggs and pastries.')]},
{label:'Lambrusco',style:'Sparkling',keywords:['lambrusco'],intro:'Sparkling red, usually dry to gently off-dry. Serve it cool and it makes sense immediately.',dishes:[d('Cured meats','The regional pairing, built to cut through fat and salt.'),d('Pizza','Fizz and fruit against cheese and tomato.'),d('Barbecue','Fruity sparkling red handles smoke better than it sounds.'),d('Parmigiano','Salty, crystalline cheese and cool bubbles.')]},
{label:'Port',style:'Dessert',keywords:['port','ruby port','tawny port','vintage port','lbv','douro fortified'],intro:'Sweet and fortified. Ruby and vintage styles lead with dark fruit; tawny leans nutty, caramel and dried fruit.',tip:'Ruby for chocolate, tawny for nuts and caramel, either for blue cheese.',dishes:[d('Dark chocolate','Sweetness in the glass has to at least match the plate, and here it does.'),d('Stilton or blue cheese','Salt against sweetness is one of the oldest reliable contrasts.'),d('Walnuts and dried fruit','Especially good with tawny styles.'),d('Pecan or caramel tart','Nutty, caramelised flavors suit an aged bottle.')]},
{label:'Sauternes and sweet botrytis wines',style:'Dessert',keywords:['sauternes','botrytis','noble rot','tokaji','barsac','ice wine','eiswein'],intro:'Concentrated sweetness held up by high acidity, with honey, apricot and marmalade.',dishes:[d('Foie gras','The classic, where richness and sweetness meet head on.'),d('Blue cheese','Salt and sweetness again, in a more delicate register than Port.'),d('Fruit tart','Keep the dessert less sweet than the wine or the wine tastes thin.'),d('Crème brûlée','Caramel and custard suit the honeyed side.')]},
{label:'Moscato d’Asti',style:'Dessert',keywords:['moscato'],intro:'Lightly sweet, lightly sparkling and low in alcohol. Gentle rather than rich.',dishes:[d('Fresh fruit and berries','Delicate sweetness rather than a heavy dessert wine.'),d('Panettone or sponge cake','Light cake and light fizz.'),d('Brunch pastries','Low alcohol makes it a morning-friendly option.'),d('Mildly spicy food','Sweetness cools heat when the dish is not too rich.')]},
{label:'Sherry',style:'Dessert',keywords:['sherry','fino','manzanilla','amontillado','oloroso','palo cortado','jerez'],intro:'Fortified and mostly dry, from pale and saline fino through to nutty oloroso. Only the cream styles are sweet.',tip:'Fino and manzanilla are dry, serve cold, and go stale within days of opening.',dishes:[d('Olives and salted almonds','Saline, dry styles are effectively a bar snack in a glass.'),d('Jamón','Salt and nuttiness on both sides.'),d('Fried fish','Cold fino against hot fried seafood is the Andalusian standard.'),d('Consommé or mushroom soup','Amontillado and oloroso suit savoury, umami-rich broths.')]},
{label:'Madeira',style:'Dessert',keywords:['madeira','bual','sercial','malmsey'],intro:'Fortified and deliberately oxidised, with searing acidity under the nuts and caramel. It survives weeks after opening.',dishes:[d('Nuts and aged cheese','Dry styles lean savoury and nutty.'),d('Caramel and toffee desserts','Sweeter styles echo the flavors directly.'),d('Chocolate cake','Acidity keeps a rich dessert from going flat.'),d('Clam chowder or rich soup','A historical pairing that still works.')]},
{label:'Orange and skin-contact wine',style:'White',keywords:['orange wine','skin contact','amber wine','ramato','qvevri'],intro:'White grapes fermented on their skins: tannic, savoury and often a little oxidative. It behaves more like a red.',dishes:[d('Moroccan and North African spice','Tannin and savoury depth handle complex spice blends.'),d('Fermented and pickled dishes','Kimchi, miso and pickles meet a wine with its own funk.'),d('Hard, aged cheese','Grippy texture wants salt and fat.'),d('Roast root vegetables','Earthy sweetness suits the savoury, tannic profile.')]}];
const styleProfiles:Record<string,WineProfile>={
Red:{label:'Red wine',style:'Red',keywords:[],intro:'Without the grape we can only go by weight. Lighter reds suit poultry, salmon and mushrooms; fuller reds want red meat and fat.',tip:'Add a grape or region to the bottle and Decant can be much more specific.',dishes:[d('Red meat and roasts','Protein and fat soften tannin in almost any red.'),d('Hard aged cheese','Salt and fat are a safe landing for a red you cannot place.'),d('Mushroom and earthy dishes','Savoury depth suits most reds regardless of weight.'),d('Tomato-based pasta','Reliable when the red has decent acidity.')]},
White:{label:'White wine',style:'White',keywords:[],intro:'Without the grape, assume freshness. Most dry whites suit seafood, poultry and vegetables; richer ones handle cream and butter.',tip:'Add a grape or region to the bottle and Decant can be much more specific.',dishes:[d('White fish and shellfish','The default home for a dry white.'),d('Roast or grilled chicken','Flexible enough for most white wines.'),d('Green vegetables and salads','Acidity keeps fresh, green flavors bright.'),d('Soft fresh cheese','Goat and other fresh cheeses suit almost any crisp white.')]},
'Rosé':{label:'Dry rosé',style:'Rosé',keywords:['rose'],intro:'Red-grape fruit with white-wine freshness, which makes it the easiest wine on a mixed table.',dishes:[d('Charcuterie and salty snacks','Freshness cuts salt and fat.'),d('Grilled prawns and seafood','Fruit without weight.'),d('Salads and summer vegetables','Light enough not to bury them.'),d('Tacos and gently spiced food','Flexible with lime, herbs and mild heat.')]},
Sparkling:{label:'Sparkling wine',style:'Sparkling',keywords:[],intro:'Acidity and bubbles cut salt, fat and fried texture, which makes sparkling the most flexible category at the table.',dishes:[d('Fried food','Bubbles and acidity reset the palate between bites.'),d('Salty snacks','Chips, popcorn and crackers, without irony.'),d('Oysters and raw shellfish','Clean, briny and classic.'),d('Soft cheese','Acidity balances a creamy texture.')]},
Dessert:{label:'Dessert wine',style:'Dessert',keywords:[],intro:'The rule of thumb is that the wine should be at least as sweet as the plate, or the wine will taste thin.',dishes:[d('Blue cheese','Salt against sweetness works across nearly every sweet wine.'),d('Fruit desserts','Keep the dessert lighter than the wine.'),d('Dark chocolate','Best with fortified reds rather than delicate sweet whites.'),d('Nuts and dried fruit','Especially good with aged, oxidative styles.')]}};
const styleAliases:Record<string,string>={red:'Red',white:'White',rose:'Rosé',rosé:'Rosé',sparkling:'Sparkling',dessert:'Dessert',fortified:'Dessert',sweet:'Dessert'};
export function normalizeStyle(value:unknown){const key=normalizeText(value);return styleAliases[key]||(Object.keys(styleProfiles).find(s=>normalizeText(s)===key)||'')}
const styleQueries:Record<string,string>={red:'Red','red wine':'Red',white:'White','white wine':'White',rose:'Rosé','rose wine':'Rosé',pink:'Rosé','pink wine':'Rosé',sparkling:'Sparkling','sparkling wine':'Sparkling',bubbles:'Sparkling',bubbly:'Sparkling',fizz:'Sparkling',dessert:'Dessert','dessert wine':'Dessert','sweet wine':'Dessert','fortified wine':'Dessert'};
const stopWords=new Set(['and','the','with','for','your','dishes','dish','led','based','other','food','style','styles','wine','wines']);
const significantWords=(value:string)=>normalizeText(value).split(' ').filter(w=>w.length>2&&!stopWords.has(w));
function derivedDishes(profile:WineProfile):Dish[]{
 const keys=profile.keywords.map(normalizeText),out:Dish[]=[];
 for(const food of pairingSources())for(const recommendation of food.recommendations){
  const shared=recommendation.keywords.some(k=>keys.includes(normalizeText(k)))||keys.some(k=>recommendation.keywords.map(normalizeText).includes(k));
  if(shared){out.push(d(food.label,recommendation.why));break}
 }
 return out;
}
function mergeDishes(curated:Dish[],derived:Dish[],limit=6){
 const out=[...curated];
 for(const candidate of derived){
  if(out.length>=limit)break;
  const words=significantWords(candidate.name);
  if(out.some(existing=>significantWords(existing.name).some(w=>words.includes(w))))continue;
  out.push(candidate);
 }
 return out.slice(0,limit);
}
const present=(profile:WineProfile,exact:boolean):WineMatch=>({label:profile.label,style:profile.style,intro:profile.intro,tip:profile.tip,keywords:profile.keywords,dishes:mergeDishes(profile.dishes,derivedDishes(profile)),exact});
function matchProfile(text:string,style?:string):WineProfile|null{
 const q=normalizeText(text);if(!q)return null;
 const wanted=style?normalizeStyle(style):'';
 // A stated style is trusted: a white Bordeaux should not be matched on the word Bordeaux alone.
 const pools=wanted?[wineProfiles.filter(p=>p.style===wanted)]:[wineProfiles];
 for(const pool of pools){
  let best:WineProfile|null=null,score=0;
  for(const profile of pool){
   const next=profile.keywords.reduce((sum,keyword)=>sum+(matchesTerm(q,keyword)?normalizeText(keyword).length:0),0);
   if(next>score){score=next;best=profile}
  }
  if(best)return best;
 }
 return null;
}
export function wineFor(query:string):WineMatch|null{
 const q=normalizeText(query);if(!q)return null;
 const profile=matchProfile(q);
 if(profile)return present(profile,true);
 const style=styleQueries[q];
 return style?present(styleProfiles[style],false):null;
}
type CellarRecord={id:string;kind:string;data:any};
export function pairingForBottle(record:CellarRecord|any):WineMatch|null{
 const data=record?.data||record||{};
 const style=normalizeStyle(data.style);
 const grape=[data.grape,data.varietal].filter(Boolean).join(' ');
 const named=[data.name,data.catalogName].filter(Boolean).join(' ');
 const place=[data.region].filter(Boolean).join(' ');
 const profile=matchProfile(grape,style)||matchProfile(named,style)||matchProfile(place,style);
 if(profile)return present(profile,true);
 return style&&styleProfiles[style]?present(styleProfiles[style],false):null;
}
export function cellarMatchesForWine(bottles:CellarRecord[],match:WineMatch|null){
 if(!match)return [];
 return bottles.filter(r=>Number(r.data.qty)>0).map(record=>{
  const bottleMatch=pairingForBottle(record);
  const compatible=!normalizeStyle(record.data.style)||normalizeStyle(record.data.style)===match.style;
  let score=compatible&&match.exact&&bottleMatch?.exact&&bottleMatch.label===match.label?20:0;
  if(!score&&match.style&&normalizeStyle(record.data.style)===match.style)score=1;
  return {record,score,exact:score>1};
 }).filter(entry=>entry.score>0).sort((a,b)=>b.score-a.score).slice(0,6);
}
export function detectPairingMode(query:string):'wine'|'food'{return wineFor(query)?'wine':'food'}
export const wineExamples=['Chianti','Pinot Noir','Champagne','Riesling','Sauvignon Blanc','Tawny Port'];
